"""Discrete symmetry transformations for a triangular gravitational-wave detector.

nessai's :mod:`nessai.flowmodel.group_mixture` can learn a discrete mixture
over a finite symmetry group that acts on the (physical) parameters, letting
the normalising flow model a single mode while the mixture accounts for the
others.  This module provides the group for a single triangular / equilateral
planar ground-based detector -- the motivating case is one Einstein Telescope
(ET) site, but nothing here is ET-specific: :class:`TriangularDetectorGroupAction`
takes the detector plane normal and vertex position as arguments, and
:class:`ETTriangleGroupAction` is only a thin subclass that fills in the ET-EMR
(Meuse-Rhine) geometry (:data:`ET_EMR_PLANE_NORMAL`, :data:`ET_EMR_VERTEX`).

In the long-wavelength / "frozen" limit the extrinsic likelihood of a single
triangular detector is invariant under an eight-element group.  This is the
exact analogue of the LISA sky-mode degeneracy summarised in Table III (and
Eqs. 63-65) of

    S. Marsat, J. G. Baker and T. Dal Canton,
    "Exploring the Bayesian parameter estimation of binary black holes with
    LISA", Phys. Rev. D 103, 083011 (2021) [arXiv:2003.00357].

Writing ``(lambda, beta, psi)`` for the source azimuth, elevation and
polarisation *in the detector-plane frame* and ``iota`` for the inclination,
the group is generated by

* a rotation of the source azimuth by ``pi / 2`` about the detector normal,
  compensated by a ``pi / 2`` shift of the polarisation (Eq. 64)::

      lambda -> lambda + k pi / 2   (k = 0, 1, 2, 3)
      psi    -> psi    + k pi / 2

  (the ``m = +-2`` pattern functions pick up an overall sign under a
  quarter turn, which the polarisation shift undoes); and

* a reflection of the source through the detector plane (Eq. 63)::

      beta -> -beta,   psi -> pi - psi,   iota -> pi - iota

  (reflecting ``beta`` swaps ``F_+`` for a ``psi``-flipped response and
  flips the sign of ``F_x``, which ``iota -> pi - iota`` compensates for the
  dominant quadrupole).

The reference phase ``phase`` is unchanged by every element of this group.
The four rotations and the two reflection states give ``4 x 2 = 8`` elements;
the group is :math:`\\mathbb{Z}_4 \\times \\mathbb{Z}_2` (abelian).

Optionally (``ETTriangleGroupAction(phase_reflection=True)``) a third
:math:`\\mathbb{Z}_2` factor ``phase -> phase + pi`` is folded in -- the
dominant-(2, 2)-mode degeneracy ``h ~ e^{-2i phi_c}`` -- giving a 16-element
group :math:`\\mathbb{Z}_4 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_2`.  This
extra symmetry is only *approximate* (higher modes / tides break it weakly),
but the group-mixture wrapper fits the per-element weights from data and
importance sampling corrects the residual, so it need not be exact.  Modes
``0..7`` are exactly the 8-element group; ``8..15`` are their
``phase``-flipped images.

Polarisation-phase coordinate
-----------------------------
For the dominant (2, 2) mode the extrinsic likelihood constrains only
``phase + sign(cos theta_jn) * psi`` (``phase + psi`` face-on, ``phase - psi``
face-off); the orthogonal combination is nearly flat.  The group wiring
therefore carries ``phase`` as the **single** bounded coordinate
``delta_phase = phase + sign(cos theta_jn) * psi``
(:class:`~nessai_gw.reparameterisations.phase.PolarisationPhaseReparameterisation`,
``polarisation-phase``) so that ridge is an explicit flow axis and ``psi`` is
left as the broad orthogonal coordinate.  ``delta_phase`` is a single
``[-1, 1)`` coordinate, *not* an ``Angle`` Cartesian pair: with the ridge
well-measured the pair's free ``chi(2)`` radius made the flow-facing marginal a
leptokurtic scale mixture (origin cusp), which the single base flow fit badly.

The sign must be taken from ``cos theta_jn``: the fundamental domain used above
canonicalises the detector-plane hemisphere (``beta_f >= 0``), *not*
face-on/off, so the folded posterior keeps a face-on/off mix and a sign-free
``phase + psi`` is the *flat* direction for the face-off part (a flow-fit study
on the ET BNS posterior, ``examples/validate_polarisation_phase.py``, made this
concrete: ``phase + psi`` fit worse than the plain ``phase`` pair, while
``phase + sign(cos theta_jn) * psi`` cut the flow NLL by ~1.5 nat).

``phase`` is group-invariant, so :class:`PrimeSpaceTriangularGroupAction` fixes
``phase_inv = delta_phase_in - sign(cos theta_jn)_in * psi_in`` on decode and
sets ``delta_phase_out = phase_inv + sign(cos theta_jn)_out * psi_out`` on
encode, from the group-transformed ``psi`` and ``cos theta_jn`` sign (a
reflection flips the sign and sends ``psi -> pi - psi``; a rotation shifts
``psi`` by ``k*pi/2``).  It is a constant shift / sign flip of the single
``delta_phase`` coordinate wrapped modulo the period, so the Jacobian stays 1.
With the default period ``2*pi`` the map is an exact bijection; ``delta_phase``
is additionally invariant modulo ``pi``.

With ``phase_reflection`` the fundamental-domain test for the extra
:math:`\\mathbb{Z}_2` is taken on ``delta_phase`` (the *flow* coordinate),
``delta_phase in [0, pi)`` -- **not** on the raw invariant ``phase``.  The two
differ by ``sign(cos theta_jn) * psi`` and ``psi`` is unconstrained, so a
raw-``phase`` cut is uncorrelated with the ``delta_phase`` the base flow
actually sees and never folds the ``delta_phase -> delta_phase + pi``
degeneracy.  ``_encode`` shifts ``delta_phase`` by ``pi`` under a
``phase``-flip, so ``delta_phase in [0, pi)`` is the matching domain.

Timing coordinate
-----------------
Unlike LISA, a ground-based triangle sits at an appreciable offset ``r_det``
(the detector ``vertex``) from the geocenter, so the sky degeneracy is only a
degeneracy of the *detector-frame* arrival time ``t_det`` -- the arrival time at
the detector centre -- not of the geocentric time ``geocent_time`` that bilby
samples.  With ``n`` the unit vector towards the source,

    t_det = geocent_time + delay(n),   delay(n) = -(n . r_det) / c

(``delay`` is bilby's ``time_delay_from_geocenter``, ``t_det - geocent_time``;
cf. Eq. 22 of Santoliquido
et al. 2025, arXiv:2504.21087, whose bimodal ``geocent_time`` posterior is
exactly this offset seen in the wrong coordinate).

The default (prime-space) wiring therefore reparameterises ``geocent_time`` to
``t_det`` (:class:`~nessai_gw.reparameterisations.time.DetectorCenterTimeReparameterisation`,
``detector-center-time``; see Tissino et al. 2026, arXiv:2606.04918,
https://arxiv.org/abs/2606.04918).  Because ``t_det`` is invariant under every
element of the frozen-limit group,
:class:`PrimeSpaceTriangularGroupAction` carries the ``t_det`` prime coordinate
through **unchanged** -- time need not be acted on at all.

The physical-space :class:`TriangularDetectorGroupAction` (the
``prime_space=False`` path and standalone
:func:`make_triangular_group_mixture_flow`) still works in ``geocent_time`` and
so must carry it along by the change in the geocenter-to-detector delay::

    geocent_time -> geocent_time + delay(n) - delay(n')

where ``n'`` is the transformed source direction.  This is an additive shift
that depends only on the (already transformed) sky position, so it leaves the
Jacobian of the whole action equal to one.

The transformations act on the *geocentric* parameters used by bilby, but in
the measure-preserving coordinates ``ra``, ``sin_dec`` (``= sin(dec)``),
``cos_theta_jn`` (``= cos(theta_jn)``), ``psi``, ``phase`` and
``geocent_time``.  The sky
rotations/reflection are isometries of the sphere, so they preserve
``d(ra) d(sin_dec)``; the reflection sends ``cos_theta_jn -> -cos_theta_jn``;
and ``psi`` only picks up constant shifts and a sign flip.  The whole action
therefore has unit Jacobian in these coordinates -- which is what
:class:`nessai.flowmodel.group_mixture.DiscreteGroupMixtureFlowWrapper`
assumes (it treats the action as measure-preserving).  In the raw angles
``dec`` / ``theta_jn`` it would *not* be, and the omitted ``cos(dec)`` /
``sin(theta_jn)`` factors wreck the importance weights.

Points are carried into the detector-plane frame, transformed there, and
carried back, using exactly bilby's polarisation-tensor convention (Nishizawa
et al. 2009), so a transformed point reproduces the antenna response of the
original one.
"""

from __future__ import annotations

import numpy as np
import torch

from . import nessai_logger
from ._geometry import SPEED_OF_LIGHT as _SPEED_OF_LIGHT
from ._geometry import greenwich_mean_sidereal_time as _greenwich_mean_sidereal_time

logger = nessai_logger.getChild(__name__)

#: Parameters the group acts on, in the order expected by the flow.  These
#: are the *measure-preserving* coordinates: ``sin_dec = sin(dec)`` and
#: ``cos_theta_jn = cos(theta_jn)`` rather than the raw angles, so the action
#: has unit Jacobian (see the module docstring).
TRIANGULAR_DETECTOR_PARAMETERS = [
    "ra",
    "sin_dec",
    "cos_theta_jn",
    "psi",
    "phase",
    "geocent_time",
]

#: Number of group elements of the long-wavelength-exact group (``Z4 x Z2``).
TRIANGULAR_DETECTOR_GROUP_SIZE = 8

#: Number of group elements with the extra (approximate) ``phase -> phase + pi``
#: (2, 2)-mode reflection folded in (``Z4 x Z2 x Z2``); see
#: :class:`TriangularDetectorGroupAction` ``phase_reflection``.
TRIANGULAR_DETECTOR_GROUP_SIZE_PHASE = 16

_TWO_PI = 2.0 * np.pi

#: Small offset guarding divisions by a vector norm in the prime-space adapter.
_EPS = 1e-30

#: nessai ``Angle`` reparameterisation convention: the Cartesian angle stored by
#: the flow is ``physical_angle * scale``.  ``angle-pi`` (used for ``psi``) has
#: ``scale = 2``.  ``psi`` is the only extrinsic coordinate still carried as an
#: ``Angle`` Cartesian pair.
_ANGLE_SCALE = {"psi": 2.0}

#: ``polarisation-phase`` scale (must match the value the ``polarisation-phase``
#: reparameterisation is registered with).  The flow coordinate is
#: ``delta_phase_prime = (((phase + sign(cos theta_jn) * psi) * scale) mod 2*pi)
#: / pi - 1`` in ``[-1, 1)``; ``scale = 1`` -> period ``2*pi`` (bijective).
_DELTA_PHASE_SCALE = 1.0

#: ``geocent_time`` prime coordinate is ``(geocent_time - reference_time) /
#: _GEOCENT_SCALE``.  A fixed scale (rather than data-driven bounds) keeps the
#: group's additive light-travel-delay shift exact under a constant offset.
#: Tuned for an ET-scale site; a very different geometry may want it revisited.
_GEOCENT_SCALE = 5e-3

#: Floor for the group-mixture wrapper's per-element canonical std.  Lowered
#: from nessai's ``1e-2`` default so a genuinely narrow prime dimension
#: (``geocent_time``) is standardised by its real width, not the floor.
#: Tuned for an ET-scale site; a very different geometry may want it revisited.
_MIN_CANON_STD = 1e-3


def detector_plane_normal(interferometers) -> np.ndarray:
    """Unit normal to the plane of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects (the three
        nested detectors of the triangle), each exposing ``geometry.x`` and
        ``geometry.y`` unit arm vectors in the Earth-fixed frame.

    Returns
    -------
    numpy.ndarray
        The mean arm-plane normal, normalised to unit length.
    """
    normals = []
    for ifo in interferometers:
        x = np.asarray(ifo.geometry.x, dtype=float)
        y = np.asarray(ifo.geometry.y, dtype=float)
        n = np.cross(x, y)
        normals.append(n / np.linalg.norm(n))
    n = np.mean(normals, axis=0)
    return n / np.linalg.norm(n)


def detector_vertex(interferometers) -> np.ndarray:
    """Mean geocentric vertex position (metres) of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects, each exposing
        ``geometry.vertex`` (its Earth-fixed position in metres).

    Returns
    -------
    numpy.ndarray
        The mean of the three vertex positions.
    """
    vertices = [
        np.asarray(ifo.geometry.vertex, dtype=float) for ifo in interferometers
    ]
    return np.mean(vertices, axis=0)


def detector_vertex_from_geodetic(
    latitude: float, longitude: float, height: float = 0.0
) -> np.ndarray:
    """Earth-fixed position (metres) from WGS84 geodetic coordinates.

    Parameters
    ----------
    latitude, longitude : float
        Geodetic latitude and longitude in radians.
    height : float, optional
        Height above the WGS84 ellipsoid in metres (default 0).
    """
    a = 6378137.0
    f = 1.0 / 298.257223563
    e2 = f * (2.0 - f)
    sin_lat = np.sin(latitude)
    n = a / np.sqrt(1.0 - e2 * sin_lat**2)
    return np.array(
        [
            (n + height) * np.cos(latitude) * np.cos(longitude),
            (n + height) * np.cos(latitude) * np.sin(longitude),
            (n * (1.0 - e2) + height) * sin_lat,
        ]
    )


def _detector_frame_basis(
    plane_normal: np.ndarray, azimuth_offset: float = 0.0
) -> np.ndarray:
    """Orthonormal Earth-fixed basis ``[e1, e2, e3]`` with ``e3`` the normal.

    ``e1`` is the (Earth-fixed) z-axis projected into the plane, then rotated
    about ``e3`` by ``azimuth_offset``.  The physical group action is
    equivariant under this in-plane rotation (it only shifts ``lambda`` and
    ``psi`` by a constant), but the *fundamental domain* -- detector-frame
    azimuth in ``[0, pi/2)`` -- is not: ``azimuth_offset`` moves the Z4 seams
    off the sky-posterior peak (see :func:`recommended_sky_azimuth_offset`).
    """
    e3 = np.asarray(plane_normal, dtype=float)
    e3 = e3 / np.linalg.norm(e3)
    e1 = np.array([0.0, 0.0, 1.0]) - e3[2] * e3
    e1 = e1 / np.linalg.norm(e1)
    e2 = np.cross(e3, e1)
    if azimuth_offset:
        c, s = np.cos(azimuth_offset), np.sin(azimuth_offset)
        e1, e2 = c * e1 + s * e2, -s * e1 + c * e2
    return np.stack([e1, e2, e3])


def _uvw(phi: torch.Tensor, theta: torch.Tensor):
    """bilby (Nishizawa 2009) frame vectors for colatitude/azimuth angles."""
    cp, sp = torch.cos(phi), torch.sin(phi)
    ct, st = torch.cos(theta), torch.sin(theta)
    zero = torch.zeros_like(phi)
    u = torch.stack([cp * ct, ct * sp, -st], dim=-1)
    v = torch.stack([-sp, cp, zero], dim=-1)
    w = torch.stack([st * cp, st * sp, ct], dim=-1)
    return u, v, w


def _polarisation_angle(m: torch.Tensor, u: torch.Tensor, v: torch.Tensor):
    """Recover ``psi`` from ``m``, where ``m = -u sin psi - v cos psi``."""
    return torch.atan2(-(m * u).sum(-1), -(m * v).sum(-1))


class TriangularDetectorGroupAction:
    """Callable eight-element group action for a triangular detector.

    Detector-agnostic: the only inputs that depend on the instrument are the
    Earth-fixed plane normal and vertex position.  :class:`ETTriangleGroupAction`
    is a thin subclass that fills those in with the ET-EMR geometry.

    Instances are the ``group_action_fn`` /  ``in_fundamental_domain`` pair
    consumed by :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event.  Only the Greenwich mean sidereal
        time it implies is used (to rotate between the equatorial and
        Earth-fixed frames); the ~tens-of-ms spread of a posterior is
        negligible here.
    plane_normal : array_like
        Unit normal to the detector plane in the Earth-fixed frame.  Use
        :func:`detector_plane_normal` to build one from a bilby interferometer
        list.
    vertex : array_like
        Geocentric position of the detector (metres, Earth-fixed frame), used
        to carry ``geocent_time`` along with the sky transformation.  Use
        :func:`detector_vertex` to build one from a bilby interferometer list.
    phase_reflection : bool, optional
        If ``True``, fold in the extra ``phase -> phase + pi`` (2, 2)-mode
        degeneracy as a third ``Z2`` factor, giving a **16-element** group
        (``group_size = 16``).  This symmetry is only *approximate* (higher
        modes / tides break it weakly) -- the group-mixture wrapper fits the
        per-element weights from data and importance sampling corrects the
        residual, so nothing here needs it to be exact.  Default ``False``
        (the long-wavelength-exact 8-element group).
    """

    parameters = TRIANGULAR_DETECTOR_PARAMETERS
    group_size = TRIANGULAR_DETECTOR_GROUP_SIZE

    def __init__(
        self,
        reference_time,
        plane_normal,
        vertex,
        phase_reflection=False,
        azimuth_offset=0.0,
        polarisation_quarter=False,
    ):
        self.reference_time = float(reference_time)
        #: Fold the (2, 2)-mode polarisation/phase quarter turn
        #: ``{psi -> psi + pi/2, phase -> phase - pi/2}`` -- promotes the phase
        #: sector from a ``Z2`` (``phase -> phase + pi``, its square) to a
        #: ``Z4`` and doubles the group to 32.  Implies ``phase_reflection``.
        self.polarisation_quarter = bool(polarisation_quarter)
        self.phase_reflection = (
            bool(phase_reflection) or self.polarisation_quarter
        )
        #: In-plane rotation (rad) of the detector frame about the plane
        #: normal; moves the Z4 fundamental-domain seams off the sky peak.
        self.azimuth_offset = float(azimuth_offset)
        #: Instance attribute (shadows the class default): 32 with the
        #: polarisation/phase quarter turn, 16 with ``phase -> phase + pi``,
        #: else 8.
        self.group_size = (
            2 * TRIANGULAR_DETECTOR_GROUP_SIZE_PHASE
            if self.polarisation_quarter
            else TRIANGULAR_DETECTOR_GROUP_SIZE_PHASE
            if self.phase_reflection
            else TRIANGULAR_DETECTOR_GROUP_SIZE
        )
        self.gmst = _greenwich_mean_sidereal_time(self.reference_time)
        self.plane_normal = np.asarray(plane_normal, dtype=float)
        self._basis_np = _detector_frame_basis(
            self.plane_normal, self.azimuth_offset
        )
        self._basis = torch.as_tensor(self._basis_np, dtype=torch.float64)
        self.vertex = np.asarray(vertex, dtype=float)
        self._vertex = torch.as_tensor(self.vertex, dtype=torch.float64)

        # Equatorial (ra-based) Cartesian sky vector -> detector-frame vector,
        # with GMST folded in: ``w_f = R @ w_eq`` where
        # ``w_eq = (cos dec cos ra, cos dec sin ra, sin dec)`` and ``w_f`` is
        # ``(cos beta_f cos lam_f, cos beta_f sin lam_f, sin beta_f)`` -- the
        # same detector-frame direction :meth:`_to_frame` computes.  ``Rz``
        # maps ``ra -> ra - gmst``; ``_basis_np`` (rows e1, e2, e3=normal) then
        # rotates Earth-fixed -> detector frame.  Used by
        # :class:`RotatedAnglePair` (flow coordinates) and
        # :class:`PrimeSpaceTriangularGroupAction` (prime-space decode/encode).
        _g = self.gmst
        _Rz = np.array(
            [
                [np.cos(_g), np.sin(_g), 0.0],
                [-np.sin(_g), np.cos(_g), 0.0],
                [0.0, 0.0, 1.0],
            ]
        )
        self.sky_frame_rotation = self._basis_np @ _Rz

    # -- coordinate maps ------------------------------------------------

    def _to_frame(self, ra, dec, psi):
        """Equatorial ``(ra, dec, psi)`` -> detector-frame angles."""
        basis = self._basis.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        u, v, w = _uvw(phi, theta)
        m = -u * torch.sin(psi)[..., None] - v * torch.cos(psi)[..., None]
        w_f = w @ basis.T
        m_f = m @ basis.T
        theta_f = torch.acos(torch.clamp(w_f[..., 2], -1.0, 1.0))
        lam_f = torch.atan2(w_f[..., 1], w_f[..., 0])
        u_f, v_f, _ = _uvw(lam_f, theta_f)
        psi_f = _polarisation_angle(m_f, u_f, v_f)
        beta_f = 0.5 * np.pi - theta_f
        return lam_f, beta_f, psi_f

    def _from_frame(self, lam_f, beta_f, psi_f):
        """Detector-frame angles -> equatorial ``(ra, dec, psi)``."""
        basis = self._basis.to(lam_f.dtype)
        theta_f = 0.5 * np.pi - beta_f
        u_f, v_f, w_f = _uvw(lam_f, theta_f)
        sin_psi = torch.sin(psi_f)[..., None]
        cos_psi = torch.cos(psi_f)[..., None]
        m_f = -u_f * sin_psi - v_f * cos_psi
        w = w_f @ basis
        m = m_f @ basis
        dec = torch.asin(torch.clamp(w[..., 2], -1.0, 1.0))
        phi = torch.atan2(w[..., 1], w[..., 0])
        ra = torch.remainder(phi + self.gmst, _TWO_PI)
        u, v, _ = _uvw(ra - self.gmst, 0.5 * np.pi - dec)
        psi = torch.remainder(_polarisation_angle(m, u, v), np.pi)
        return ra, dec, psi

    def _geocenter_delay(self, ra, dec):
        """Geocenter-to-detector light-travel delay ``t_det - geocent_time``.

        Equal to ``-(n . r_det) / c`` with ``n`` the unit vector towards the
        source, matching bilby's ``time_delay_from_geocenter`` convention.
        """
        vertex = self._vertex.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        st = torch.sin(theta)
        n = torch.stack(
            [st * torch.cos(phi), st * torch.sin(phi), torch.cos(theta)],
            dim=-1,
        )
        return -(n * vertex).sum(-1) / _SPEED_OF_LIGHT

    # -- group action -------------------------------------------------

    def _decode(self, modes: torch.Tensor):
        """Split a mode index into ``(k, reflected, phase_step)``.

        ``k`` in ``0..3`` is the ``Z4`` sky rotation, ``reflected`` the ``Z2``
        detector-plane reflection.  ``phase_step`` is the phase-sector element:
        a bool ``phase -> phase + pi`` flag for the 8/16-element group, or an
        int ``0..3`` (``modes // 8``) for the 32-element polarisation/phase
        ``Z4`` -- ``{psi -> psi + step*pi/2, phase -> phase - step*pi/2}``
        (``step = 2`` reproduces the ``phase -> phase + pi`` flip).
        """
        k = torch.remainder(modes, 4).to(torch.float64)
        reflected = (
            torch.remainder(torch.div(modes, 4, rounding_mode="floor"), 2) == 1
        )
        step = torch.div(modes, 8, rounding_mode="floor")
        if self.polarisation_quarter:
            return k, reflected, torch.remainder(step, 4)
        return k, reflected, step == 1

    def _invert_modes(self, modes: torch.Tensor) -> torch.Tensor:
        """Index of the inverse element (the group is abelian)."""
        k = torch.remainder(modes, 4)
        refl = torch.remainder(torch.div(modes, 4, rounding_mode="floor"), 2)
        pf = torch.div(modes, 8, rounding_mode="floor")
        if self.polarisation_quarter:
            pf = torch.remainder(-pf, 4)
        return pf * 8 + refl * 4 + torch.remainder(-k, 4)

    # Public aliases of the mode helpers, for callers (e.g.
    # :class:`PrimeSpaceTriangularGroupAction`) that need to inspect group
    # elements without reaching into private names.
    def decode_modes(self, modes):
        """Split a mode index into ``(k, reflected, phase_step)``."""
        return self._decode(torch.as_tensor(modes))

    def invert_modes(self, modes):
        """Index of the inverse element (the group is abelian)."""
        return self._invert_modes(torch.as_tensor(modes))

    def __call__(self, point_dict: dict, modes, inverse: bool = False) -> dict:
        """Apply the group element ``modes`` (or its inverse) to each point."""
        ra = point_dict["ra"]
        sin_dec = point_dict["sin_dec"]
        psi = point_dict["psi"]
        cos_theta_jn = point_dict["cos_theta_jn"]
        phase = point_dict["phase"]

        dec = torch.asin(torch.clamp(sin_dec, -1.0, 1.0))

        modes = torch.as_tensor(modes, device=ra.device)
        if inverse:
            modes = self._invert_modes(modes)
        k, reflected, phase_step = self._decode(modes)
        k = k.to(ra.dtype)
        quarter = 0.5 * np.pi * k

        lam_f, beta_f, psi_f = self._to_frame(ra, dec, psi)

        lam_f = lam_f + quarter
        beta_f = torch.where(reflected, -beta_f, beta_f)
        psi_f = torch.where(reflected, np.pi - psi_f, psi_f) + quarter
        # theta_jn -> pi - theta_jn under a reflection, i.e. a sign flip of
        # cos(theta_jn) -- unit Jacobian in this coordinate.
        cos_theta_jn = torch.where(
            reflected, -cos_theta_jn, cos_theta_jn
        )

        ra_t, dec_t, psi_t = self._from_frame(lam_f, beta_f, psi_f)

        if self.polarisation_quarter:
            # (2, 2)-mode polarisation/phase quarter turn:
            # psi -> psi + step*pi/2, phase -> phase - step*pi/2 (step in 0..3;
            # step == 2 is the phase -> phase + pi flip).
            shift = 0.5 * np.pi * phase_step.to(ra.dtype)
            psi_t = torch.remainder(psi_t + shift, np.pi)
            phase_t = torch.remainder(phase - shift, _TWO_PI)
        else:
            # Extra (2, 2)-mode reflection: phase -> phase + pi (16-element group).
            phase_t = torch.where(
                phase_step, torch.remainder(phase + np.pi, _TWO_PI), phase
            )

        out = {
            "ra": ra_t,
            "sin_dec": torch.sin(dec_t),
            "cos_theta_jn": cos_theta_jn,
            "psi": psi_t,
            "phase": phase_t,
        }

        # Physical-space path only: the sky degeneracy fixes the detector-frame
        # arrival time, not the geocentric one, so carry geocent_time along by
        # the change in the geocenter-to-detector delay (Santoliquido et al.
        # 2025, Eq. 22).  The prime-space adapter instead reparameterises to the
        # invariant detector-centre time and omits this key entirely (Tissino et
        # al. 2026, arXiv:2606.04918).
        if "geocent_time" in point_dict:
            out["geocent_time"] = (
                point_dict["geocent_time"]
                + self._geocenter_delay(ra, dec)
                - self._geocenter_delay(ra_t, dec_t)
            )

        return out

    def in_fundamental_domain(self, point_dict: dict) -> torch.Tensor:
        """Boolean mask: is each point the canonical point of its orbit?

        The canonical point is the one whose detector-frame azimuth lies in
        ``[0, pi / 2)`` and which sits on the ``beta >= 0`` side of the
        detector plane -- exactly one of the eight images of a generic point.
        With ``phase_reflection`` it is additionally the one with
        ``phase in [0, pi)`` -- one of the sixteen images.
        """
        dec = torch.asin(torch.clamp(point_dict["sin_dec"], -1.0, 1.0))
        lam_f, beta_f, _ = self._to_frame(
            point_dict["ra"], dec, point_dict["psi"]
        )
        in_quarter = torch.remainder(lam_f, _TWO_PI) < 0.5 * np.pi
        mask = in_quarter & (beta_f >= 0.0)
        if self.phase_reflection:
            mask = mask & (
                torch.remainder(point_dict["phase"], _TWO_PI) < np.pi
            )
        if self.polarisation_quarter:
            # phase-sector Z4: also fold psi to [0, pi/2)
            mask = mask & (
                torch.remainder(point_dict["psi"], np.pi) < 0.5 * np.pi
            )
        return mask


def make_triangular_group_mixture_flow(
    reference_time,
    plane_normal,
    vertex,
    parameters=None,
    phase_reflection=False,
    azimuth_offset=0.0,
):
    """Build a group-mixture ``FlowModel`` class for a triangular detector.

    Thin wrapper around
    :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow` bound to
    :class:`TriangularDetectorGroupAction`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event (see
        :class:`TriangularDetectorGroupAction`).
    plane_normal : array_like
        Earth-fixed unit normal to the detector plane.
    vertex : array_like
        Geocentric detector position (metres).
    parameters : list of str, optional
        Override the acted-on parameter names/order (default
        :data:`TRIANGULAR_DETECTOR_PARAMETERS`).  The flow must be given exactly
        these inputs, in this order.
    phase_reflection : bool, optional
        Fold in the extra ``phase -> phase + pi`` (2, 2)-mode degeneracy
        (16-element group).  See :class:`TriangularDetectorGroupAction`.

    Returns
    -------
    type
        A ``GroupMixtureFlowModel`` subclass, suitable as ``_FlowModelClass``
        of a :class:`nessai.flowmodel.group_mixture.GroupFlowProposal` (or the
        ``flow_class`` of a flow config).
    """
    from nessai.flowmodel.group_mixture import make_group_mixture_flow

    action = TriangularDetectorGroupAction(
        reference_time=reference_time,
        plane_normal=plane_normal,
        vertex=vertex,
        phase_reflection=phase_reflection,
        azimuth_offset=azimuth_offset,
    )
    names = list(parameters) if parameters is not None else action.parameters
    return make_group_mixture_flow(
        group_action_fn=action,
        group_size=action.group_size,
        param_names=names,
        in_fundamental_domain=action.in_fundamental_domain,
    )


# ---------------------------------------------------------------------------
# Prime-space adapter + proposal wiring
#
# nessai's :class:`~nessai.flowmodel.group_mixture.GroupFlowProposalMixin` can
# run :class:`TriangularDetectorGroupAction` directly in the *physical* parameter
# space and bridge to the flow's *prime* space with a
# :class:`~nessai.flowmodel.group_mixture.ReparamBridge` (non-affine
# reparameterisations handled exactly).  That is the ``prime_space=False`` path
# of :func:`make_triangular_group_flow_proposal` and needs no code here.
#
# The ``prime_space=True`` path instead maps the acted physical coordinates out
# of the nessai-gw prime vector, runs the unchanged group action, and re-encodes
# onto vectors of the *same* radii -- an exact unit-Jacobian prime-space map with
# no per-call numpy round-trip through the reparameterisation.  This mirrors the
# wiring tuned in the ``xG_inference`` ET replay optimisation.
# ---------------------------------------------------------------------------


def _angle_from_pair(x, y, scale):
    """Physical angle from a nessai ``Angle`` Cartesian pair (radius returned)."""
    radius = torch.hypot(x, y)
    angle = torch.remainder(torch.atan2(y, x), _TWO_PI) / scale
    return angle, radius


def _pair_from_angle(angle, radius, scale):
    """Inverse of :func:`_angle_from_pair`."""
    a = angle * scale
    return radius * torch.cos(a), radius * torch.sin(a)


def _decode_pair(point_dict, pair, scale):
    x, y = point_dict[pair[0]], point_dict[pair[1]]
    return _angle_from_pair(x, y, scale)


class PrimeSpaceTriangularGroupAction:
    """Apply :class:`TriangularDetectorGroupAction` in the nessai-gw *prime* space.

    Discovers the sky / ``psi`` / ``phase`` / ``theta_jn`` / ``t_det`` prime
    coordinates from the flow's actual ``prime_parameters`` and threads the
    acted subset through the unchanged group action, re-encoding onto
    same-radius vectors so the prime-space map is exactly a rotation /
    reflection / constant shift with unit Jacobian.  The detector-centre
    arrival time ``t_det`` is invariant under the group and is carried through
    untouched (Tissino et al. 2026, arXiv:2606.04918).

    Instances are passed to
    :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow` as the
    ``prime_space_action`` / ``prime_space_in_domain`` pair.

    Parameters
    ----------
    action : TriangularDetectorGroupAction
        The physical-space group action.
    prime_names : list of str
        The flow's prime-parameter names, in order.  Re-bind after the proposal
        is initialised with :meth:`bind`.
    """

    def __init__(self, action, prime_names):
        self._action = action
        # Flow sky coordinates are detector-frame (see RotatedAnglePair); the
        # decode/encode below work in equatorial coordinates, so rotate in and
        # out with the action's fixed sky-frame rotation.
        self._sky_R = torch.as_tensor(
            action.sky_frame_rotation, dtype=torch.float64
        )
        self.bind(prime_names)

    # -- binding -----------------------------------------------------------

    def bind(self, prime_names):
        """(Re)bind to the flow's actual prime-parameter order."""
        self._prime_names = list(prime_names)
        names = set(self._prime_names)

        # sky: ra_dec_{x,y,z} from the sky-ra-dec AnglePair (3-coord path) or
        # sky_u / sky_v from EqualAreaSky (2-coord path).
        self._sky = None
        self._sky2d = None
        if "sky_u" in names and "sky_v" in names:
            self._sky2d = ("sky_u", "sky_v")
        else:
            for prefix in ("ra_dec", "dec_ra"):
                trip = [f"{prefix}_{c}" for c in ("x", "y", "z")]
                if all(t in names for t in trip):
                    self._sky = tuple(trip)
                    break

        # psi: name_{x,y} from the angle-pi Angle reparam, or a single
        # ``psi_prime`` coordinate from SingleAngleReparameterisation.
        self._pair = {}
        for base in _ANGLE_SCALE:
            x, y = f"{base}_x", f"{base}_y"
            if x in names and y in names:
                self._pair[base] = (x, y)
        self._psi_single = (
            "psi_prime" in names and "psi" not in self._pair
        )

        # delta_phase: single linear polarisation-phase coordinate
        self._delta_phase = None
        for cand in ("delta_phase", "delta_phase_prime"):
            if cand in names:
                self._delta_phase = cand
                break

        # theta_jn: single linear angle-sine coordinate
        self._theta_jn = None
        for cand in ("theta_jn_prime", "theta_jn"):
            if cand in names:
                self._theta_jn = cand
                break

        # detector-centre arrival time: invariant, carried through unchanged
        # (detector-center-time reparameterisation).
        self._t_det = None
        for cand in ("t_det", "t_det_prime", "detector_time", "geocent_time"):
            if cand in names:
                self._t_det = cand
                break

        missing = []
        if self._sky is None and self._sky2d is None:
            missing.append("sky-ra-dec (ra_dec_x/_y/_z) or sky_u/sky_v")
        if "psi" not in self._pair and not self._psi_single:
            missing.append("psi (psi_x/_y or psi_prime)")
        if self._delta_phase is None:
            missing.append("delta_phase")
        if self._theta_jn is None:
            missing.append("theta_jn")
        if self._t_det is None:
            missing.append("t_det")
        if missing:
            raise RuntimeError(
                f"prime space is missing {missing}, which the triangular-detector "
                "group action needs; the prime-space path only applies to a "
                "single-site triangular-detector run with the standard extrinsic parameters and "
                "the nessai-gw reparameterisations (sky-ra-dec, angle-pi, "
                "polarisation-phase, angle-sine, detector-center-time)."
            )

    # -- decode / encode -------------------------------------------------

    def _decode(self, point_dict):
        """nessai-gw prime dict -> ``TriangularDetectorGroupAction`` coordinate dict.

        Returns ``(acted, aux)`` where ``aux`` carries the radii needed to
        re-encode.
        """
        if self._sky2d is not None:
            # EqualAreaSky: (sky_u, sky_v) -> detector-frame unit vector.
            u = point_dict[self._sky2d[0]]
            v = point_dict[self._sky2d[1]]
            Rt = self._sky_R.to(u.dtype)
            lam_f = _TWO_PI * u
            z_f = torch.clamp(1.0 - 2.0 * v, -1.0, 1.0)
            rho = torch.sqrt(torch.clamp(1.0 - z_f * z_f, min=0.0))
            dx = rho * torch.cos(lam_f)
            dy = rho * torch.sin(lam_f)
            dz = z_f
            r_sky = torch.ones_like(u)
        else:
            dx, dy, dz = (point_dict[n] for n in self._sky)
            Rt = self._sky_R.to(dx.dtype)
            r_sky = torch.sqrt(dx * dx + dy * dy + dz * dz + _EPS)
        # detector-frame (flow) -> equatorial: v_eq = R^T v_det
        sx = Rt[0, 0] * dx + Rt[1, 0] * dy + Rt[2, 0] * dz
        sy = Rt[0, 1] * dx + Rt[1, 1] * dy + Rt[2, 1] * dz
        sz = Rt[0, 2] * dx + Rt[1, 2] * dy + Rt[2, 2] * dz
        norm = torch.sqrt(sx * sx + sy * sy + sz * sz + _EPS)
        ra = torch.remainder(torch.atan2(sy, sx), _TWO_PI)
        sin_dec = torch.clamp(sz / norm, -1.0, 1.0)

        if self._psi_single:
            ang = point_dict["psi_prime"]
            psi = torch.remainder(
                (ang + 1.0) * np.pi / _ANGLE_SCALE["psi"], np.pi
            )
            r_psi = torch.ones_like(psi)
        else:
            psi, r_psi = _decode_pair(
                point_dict, self._pair["psi"], _ANGLE_SCALE["psi"]
            )

        # theta_jn is decoupled from the frame rotation: the group only ever
        # sends cos(theta_jn) -> -cos(theta_jn) under a reflection, i.e. the
        # angle-sine coordinate ``u = 2 theta_jn / pi - 1`` -> ``-u`` (centre 0).
        # Handled directly in :meth:`_encode`; the value passed to the action is
        # a dummy.  ``sign(cos theta_jn) = -sign(u)`` is what the phase
        # coordinate needs.
        u_theta = point_dict[self._theta_jn]
        sign_ct = -torch.sign(u_theta)
        cos_theta_jn = torch.zeros_like(ra)

        # The flow carries the single coordinate
        # ``delta_phase_prime = (delta_phase * scale mod 2*pi) / pi - 1`` with
        # ``delta_phase = phase + sign(cos theta_jn) * psi`` (polarisation-phase).
        # ``phase`` itself is group-invariant, so recover the invariant piece and
        # let :meth:`_encode` rebuild delta_phase from the group-transformed psi
        # and cos(theta_jn) sign.
        delta_phase = torch.remainder(
            (point_dict[self._delta_phase] + 1.0) * np.pi / _DELTA_PHASE_SCALE,
            _TWO_PI,
        )
        phase = delta_phase - sign_ct * psi

        # The flow coordinate is the detector-centre arrival time (invariant
        # under the group), so it is not decoded here -- :meth:`_encode` copies
        # it through unchanged.

        acted = {
            "ra": ra,
            "sin_dec": sin_dec,
            "cos_theta_jn": cos_theta_jn,
            "psi": psi,
            "phase": phase,
        }
        aux = {
            "r_sky": r_sky,
            "r_psi": r_psi,
            "phase_inv": phase,
            "sign_ct": sign_ct,
        }
        return acted, aux

    def _encode(self, point_dict, mapped, aux):
        out = dict(point_dict)

        ra_t = mapped["ra"]
        sin_dec_t = torch.clamp(mapped["sin_dec"], -1.0, 1.0)
        cos_dec_t = torch.sqrt(torch.clamp(1.0 - sin_dec_t ** 2, min=0.0))
        # equatorial -> detector-frame (flow): v_det = R v_eq
        Rf = self._sky_R.to(cos_dec_t.dtype)
        ux = cos_dec_t * torch.cos(ra_t)
        uy = cos_dec_t * torch.sin(ra_t)
        uz = sin_dec_t
        dxf = Rf[0, 0] * ux + Rf[0, 1] * uy + Rf[0, 2] * uz
        dyf = Rf[1, 0] * ux + Rf[1, 1] * uy + Rf[1, 2] * uz
        dzf = Rf[2, 0] * ux + Rf[2, 1] * uy + Rf[2, 2] * uz
        if self._sky2d is not None:
            lam_f = torch.remainder(torch.atan2(dyf, dxf), _TWO_PI)
            z_f = torch.clamp(dzf, -1.0, 1.0)
            out[self._sky2d[0]] = lam_f / _TWO_PI
            out[self._sky2d[1]] = 0.5 * (1.0 - z_f)
        else:
            r = aux["r_sky"]
            sx, sy, sz = self._sky
            out[sx] = r * dxf
            out[sy] = r * dyf
            out[sz] = r * dzf

        if self._psi_single:
            a = torch.remainder(
                mapped["psi"] * _ANGLE_SCALE["psi"], _TWO_PI
            )
            out["psi_prime"] = a / np.pi - 1.0
        else:
            px, py = self._pair["psi"]
            out[px], out[py] = _pair_from_angle(
                mapped["psi"], aux["r_psi"], _ANGLE_SCALE["psi"]
            )

        u = point_dict[self._theta_jn]
        out[self._theta_jn] = torch.where(aux["reflected"], -u, u)

        # delta_phase = phase_invariant + sign(cos theta_jn)_out * psi_out.
        # The reflection flips both sign(cos theta_jn) and psi (psi -> pi - psi,
        # via mapped["psi"]); a rotation leaves the sign and shifts psi; the
        # extra (2, 2) reflection adds pi to the invariant phase piece.
        sign_ct_out = torch.where(
            aux["reflected"], -aux["sign_ct"], aux["sign_ct"]
        )
        if self._action.polarisation_quarter:
            # phase sector Z4: the invariant phase piece shifts by
            # -step*pi/2; mapped["psi"] already carries +step*pi/2, so
            # delta_phase stays invariant for the face-on branch and shifts
            # by -step*pi for the face-off one.
            phase_inv_out = aux["phase_inv"] - 0.5 * np.pi * aux[
                "phase_step"
            ].to(aux["phase_inv"].dtype)
        else:
            phase_inv_out = torch.where(
                aux["phase_step"], aux["phase_inv"] + np.pi, aux["phase_inv"]
            )
        delta_phase_new = phase_inv_out + sign_ct_out * mapped["psi"]
        angle = torch.remainder(
            delta_phase_new * _DELTA_PHASE_SCALE, _TWO_PI
        )
        out[self._delta_phase] = angle / np.pi - 1.0

        # Detector-centre arrival time is group-invariant: carried through
        # unchanged from ``point_dict`` (via ``out = dict(point_dict)``).
        return {n: out[n] for n in self._prime_names}

    # -- interface ------------------------------------------------------

    def _mode_masks(self, modes, inverse):
        modes = torch.as_tensor(modes)
        if inverse:
            modes = self._action.invert_modes(modes)
        _, reflected, phase_step = self._action.decode_modes(modes)
        return reflected, phase_step

    def __call__(self, point_dict, modes, inverse: bool = False):
        acted, aux = self._decode(point_dict)
        mapped = self._action(acted, modes, inverse=inverse)
        aux["reflected"], aux["phase_step"] = self._mode_masks(
            modes, inverse
        )
        return self._encode(point_dict, mapped, aux)

    def in_fundamental_domain(self, point_dict):
        acted, aux = self._decode(point_dict)
        if self._action.phase_reflection:
            # The base action folds the phase-reflection Z2 by testing
            # ``phase in [0, pi)`` on the raw invariant phase.  In prime space
            # the flow coordinate is ``delta_phase = phase + sign_ct * psi``,
            # not the raw phase, and psi is unconstrained -- so the raw-phase
            # cut is ~a coin flip w.r.t. delta_phase and never actually folds
            # the ``delta_phase -> delta_phase + pi`` (2, 2)-mode degeneracy the
            # base flow sees.  ``_encode`` under ``phase_flipped`` shifts
            # delta_phase by pi, so ``delta_phase in [0, pi)`` is the matching
            # fundamental domain -- test that instead (base uses ``phase`` only
            # for this clause).
            acted = dict(acted)
            acted["phase"] = acted["phase"] + aux["sign_ct"] * acted["psi"]
        return self._action.in_fundamental_domain(acted)


_LOG_2PI = float(np.log(2.0 * np.pi))
_HALF_LOG_2PI = 0.5 * _LOG_2PI


def _log_std_normal_pdf(x):
    return -0.5 * x * x - _HALF_LOG_2PI


class SkyOctantGaussianiser:
    """Cylindrical equal-area + probit map of the canonical sky octant.

    A ``canonical_transform`` for
    :class:`nessai.flowmodel.group_mixture.DiscreteGroupMixtureFlowWrapper`.
    Once the triangular-detector group has folded the sky to the axis-aligned
    detector-frame octant ``x, y, z >= 0`` (see
    :class:`~nessai_gw.reparameterisations.sky.RotatedAnglePair`), the base
    flow still sees the *uniform-on-sphere* prior restricted to that octant --
    a distribution with a hard edge along every octant boundary, which a
    Gaussian-latent flow fits badly.

    This transform replaces the three canonical Cartesian sky coordinates
    ``(x, y, z) = r * (sin th cos ph, sin th sin ph, cos th)`` with

    * ``a = Phi^-1( (2/pi) * ph )``      (azimuth ``ph in [0, pi/2)``  -> ``U`` -> ``N(0, 1)``)
    * ``b = Phi^-1( 1 - z / r )``        (``z/r = cos th in [0, 1]``   -> ``U`` -> ``N(0, 1)``)
    * ``c = r``                          (the auxiliary radius, passed through)

    ``(ph, z/r)`` are the equal-area (Lambert cylindrical) coordinates of the
    octant, so under the uniform-on-sphere prior ``a`` and ``b`` are *exactly*
    independent standard normals and the base flow sees no edge. The group
    action, the fundamental-domain predicate and every conjugation Jacobian
    stay in the untouched Cartesian frame -- this map only sits between the
    canonical representative and the base flow.

    The sky is detector-frame-rotated by ``RotatedAnglePair``, so the octant is
    already axis-aligned in the flow's ``ra_dec_{x,y,z}`` prime coordinates and
    no rotation is needed here.  ``reflect_parameters`` for the sky is
    incompatible with (and made redundant by) this transform: the octant walls
    are pushed to ``a, b -> -inf``.

    Jacobian (sky block only; all other coordinates are identity)::

        dx dy dz = r**2 dr dph d(z/r)             (spherical volume element)
        dph      = (pi/2) phi(a) da
        d(z/r)   = phi(b) db
        =>  log|d(a, b, c)/d(x, y, z)|
              = log(2/pi) - 2 log r - log phi(a) - log phi(b)
    """

    def __init__(self, param_names=None, eps: float = 1e-7):
        self._eps = float(eps)
        self._idx = None
        if param_names is not None:
            self.bind(param_names)

    def bind(self, param_names):
        names = list(param_names)
        trip = None
        for prefix in ("ra_dec", "dec_ra"):
            cand = [f"{prefix}_{c}" for c in ("x", "y", "z")]
            if all(c in names for c in cand):
                trip = cand
                break
        if trip is None:
            raise RuntimeError(
                "SkyOctantGaussianiser needs ra_dec_{x,y,z} (or dec_ra_*) in "
                f"the prime parameters; got {names}."
            )
        self._idx = [names.index(c) for c in trip]

    # -- transform ------------------------------------------------------

    def forward(self, canon):
        """``canon -> (t, log|det dt/dcanon|)`` (sky block gaussianised)."""
        ix, iy, iz = self._idx
        x, y, z = canon[:, ix], canon[:, iy], canon[:, iz]
        r = torch.sqrt(x * x + y * y + z * z + _EPS)
        lam = torch.atan2(y, x)
        u = torch.clamp((2.0 / np.pi) * lam, self._eps, 1.0 - self._eps)
        v = torch.clamp(1.0 - z / r, self._eps, 1.0 - self._eps)
        a = torch.special.ndtri(u)
        b = torch.special.ndtri(v)

        t = canon.clone()
        t[:, ix] = a
        t[:, iy] = b
        t[:, iz] = r
        log_j = (
            -np.log(np.pi / 2.0)
            - 2.0 * torch.log(r)
            - _log_std_normal_pdf(a)
            - _log_std_normal_pdf(b)
        )
        return t, log_j

    def inverse(self, t):
        """``t -> (canon, log|det dcanon/dt|)``."""
        ix, iy, iz = self._idx
        a, b, r = t[:, ix], t[:, iy], t[:, iz]
        u = torch.special.ndtr(a)
        v = torch.special.ndtr(b)
        lam = (np.pi / 2.0) * u
        cos_th = torch.clamp(1.0 - v, -1.0, 1.0)
        sin_th = torch.sqrt(torch.clamp(1.0 - cos_th * cos_th, min=0.0))
        rho = r * sin_th

        canon = t.clone()
        canon[:, ix] = rho * torch.cos(lam)
        canon[:, iy] = rho * torch.sin(lam)
        canon[:, iz] = r * cos_th
        log_j = (
            np.log(np.pi / 2.0)
            + 2.0 * torch.log(r)
            + _log_std_normal_pdf(a)
            + _log_std_normal_pdf(b)
        )
        return canon, log_j


_SKY_PROBIT_EPS = 1e-7


class SkyOctantProbit:
    """Probit of the folded equal-area sky sub-square (2-coordinate sky path).

    ``canonical_transform`` companion to
    :class:`nessai_gw.reparameterisations.sky.EqualAreaSky`.  After the
    triangular-detector group has folded the equal-area sky coordinates to the
    fundamental sub-square ``sky_u in [0, 1/4), sky_v in [0, 1/2)`` (the ``Z4``
    in-plane rotation acts by ``u -> u + k/4 mod 1`` and the ``Z2`` reflection
    by ``v -> 1 - v``), this maps that sub-square back to two independent
    standard normals::

        a = Phi^-1(4 * sky_u)          sky_u in [0, 1/4)  ->  N(0, 1)
        b = Phi^-1(2 * sky_v)          sky_v in [0, 1/2)  ->  N(0, 1)

    Under the uniform-on-sphere prior ``4 sky_u`` and ``2 sky_v`` are exactly
    ``U(0, 1)`` so ``a`` and ``b`` are exactly ``N(0, 1)`` and the base flow
    sees no octant edge.  There is **no radial coordinate**: unlike
    :class:`SkyOctantGaussianiser` this keeps the base-flow sky block 2-D.

    Jacobian (sky block only)::

        log|d(a, b)/d(sky_u, sky_v)| = log 8 - log phi(a) - log phi(b)
    """

    def __init__(self, param_names=None):
        self._iu = self._iv = None
        if param_names is not None:
            self.bind(param_names)

    def bind(self, param_names):
        names = list(param_names)
        if "sky_u" not in names or "sky_v" not in names:
            raise RuntimeError(
                "SkyOctantProbit needs sky_u / sky_v in the prime parameters; "
                f"got {names}."
            )
        self._iu = names.index("sky_u")
        self._iv = names.index("sky_v")

    def forward(self, canon):
        """``canon -> (t, log|det dt/dcanon|)`` (sky block probit-mapped)."""
        iu, iv = self._iu, self._iv
        u = torch.clamp(4.0 * canon[:, iu], _SKY_PROBIT_EPS, 1.0 - _SKY_PROBIT_EPS)
        v = torch.clamp(2.0 * canon[:, iv], _SKY_PROBIT_EPS, 1.0 - _SKY_PROBIT_EPS)
        a = torch.special.ndtri(u)
        b = torch.special.ndtri(v)
        t = canon.clone()
        t[:, iu] = a
        t[:, iv] = b
        log_j = (
            np.log(8.0)
            - _log_std_normal_pdf(a)
            - _log_std_normal_pdf(b)
        )
        return t, log_j

    def inverse(self, t):
        """``t -> (canon, log|det dcanon/dt|)``."""
        iu, iv = self._iu, self._iv
        a, b = t[:, iu], t[:, iv]
        canon = t.clone()
        canon[:, iu] = 0.25 * torch.special.ndtr(a)
        canon[:, iv] = 0.5 * torch.special.ndtr(b)
        log_j = (
            -np.log(8.0)
            + _log_std_normal_pdf(a)
            + _log_std_normal_pdf(b)
        )
        return canon, log_j


def triangular_group_reparameterisations(
    sampling_parameters, reference_time, vertex=None
):
    """Reparameterisation overrides that keep the acted parameters isometric.

    The triangular-detector group action has unit Jacobian in
    ``(ra, sin_dec, cos_theta_jn, psi, phase, geocent_time)``.  Each of those
    maps to the nessai-gw prime coordinates by an isometry *provided* the right
    reparameterisation is used:

    * ``chi_1`` / ``chi_2`` -> ``aligned-spin`` (nessai-gw CDF -> inverse-normal
      map; standard-normal prime prior, removes the log cusp at ``chi = 0``).
    * ``lambda_1`` / ``lambda_2`` -> ``logit`` with ``update_bounds=False``
      (fixed hard bounds, prime coordinate on the whole real line).
    * ``theta_jn`` -> ``angle-sine`` with ``update_bounds=False``.  The fixed,
      symmetric bounds keep the group's ``theta_jn -> pi - theta_jn`` reflection
      an exact sign flip of the prime coordinate; ``update_bounds=True`` would
      let the empirical bounds drift off ``pi/2`` and break that.
    * ``geocent_time`` -> ``detector-center-time``: the flow coordinate is the
      (affine-rescaled) arrival time at the detector centre,
      ``t_det = geocent_time + delay(ra, dec)``, which is **invariant** under the
      group -- so :class:`PrimeSpaceTriangularGroupAction` carries it through
      untouched and time is not acted on at all (Tissino et al. 2026,
      arXiv:2606.04918).  Constant ``reference_time`` shift and fixed
      :data:`_GEOCENT_SCALE` keep the GPS epoch off the flow.
    * ``phase`` -> ``polarisation-phase``: a **single** ``[-1, 1)`` coordinate
      ``delta_phase = phase + sign(cos theta_jn) * psi``, making the
      likelihood-constrained polarisation/phase combination an explicit flow
      axis instead of a thin diagonal ridge across four prime coordinates -- and
      *without* the ``Angle`` pair's free ``chi(2)`` radius, whose scale mixing
      with a well-measured ridge left a leptokurtic origin cusp the base flow
      fit poorly.  ``psi`` (``angle-pi``) and ``theta_jn`` (``angle-sine``) are
      prerequisites of this coordinate.

    Every other parameter is left to
    :meth:`nessai_gw.proposals.GWReparamMixin.add_default_reparameterisations`
    (``sky-ra-dec`` for ``ra``/``dec``, ``angle-pi`` for ``psi``,
    ``distance`` / ``mass`` for the intrinsic parameters, ...).

    This is independent of the group size: with a 16-element action
    (``phase_reflection=True``) the mixture folds ``phase <-> phase + pi``, so
    ``polarisation-phase`` stays at its default (bijective) period ``2*pi``.

    Parameters
    ----------
    sampling_parameters : iterable of str
        Every parameter nessai samples.
    reference_time : float
        Geocentric GPS time; subtracted from ``t_det`` in prime space and its
        GMST rotates the ``detector-center-time`` delay into the Earth frame.
    vertex : array_like, optional
        Earth-fixed detector position (metres) for the ``detector-center-time``
        reparameterisation.  Defaults to :data:`ET_EMR_VERTEX`; pass the value
        from :func:`detector_vertex` for a different geometry.

    Returns
    -------
    dict
        A ``reparameterisations`` mapping for ``bilby.run_sampler`` / nessai.
    """
    if vertex is None:
        vertex = ET_EMR_VERTEX

    # ``polarisation-phase`` reads x-space ``psi`` and ``theta_jn`` on its
    # inverse, and ``detector-center-time`` reads x-space ``ra`` / ``dec``, so
    # ``CombinedReparameterisation.check_order`` -- which walks the
    # reparameterisations in reverse -- needs the ``phase`` and ``geocent_time``
    # entries to sort *ahead of* the coordinates they consume on the inverse.
    # The sorter only orders by forward-input arity and keeps insertion order on
    # ties (all are arity 1) and ignores inverse inputs entirely, so we emit
    # ``phase`` / ``geocent_time`` first here.  ``psi`` (``angle-pi``) and the
    # sky ``AnglePair`` are added later by ``add_default_reparameterisations``
    # and so are always behind these.
    ordered_names = sorted(
        sampling_parameters,
        key=lambda n: 0 if n in ("phase", "geocent_time") else 1,
    )
    reps = {}
    for name in ordered_names:
        if name in ("chi_1", "chi_2"):
            reps[name] = {"reparameterisation": "aligned-spin"}
        elif name in ("lambda_1", "lambda_2"):
            reps[name] = {
                "reparameterisation": "logit",
                "update_bounds": False,
            }
        elif name == "theta_jn":
            reps[name] = {
                "reparameterisation": "angle-sine",
                "update_bounds": False,
            }
        elif name == "geocent_time":
            # t_det = geocent_time + delay(ra, dec): the invariant
            # detector-centre arrival time.  ``ra`` / ``dec`` (sky-ra-dec) are
            # prerequisites.
            reps[name] = {
                "reparameterisation": "detector-center-time",
                "vertex": [float(v) for v in np.asarray(vertex)],
                "reference_time": float(reference_time),
                "scale": _GEOCENT_SCALE,
            }
        elif name == "phase":
            # delta_phase = phase + sign(cos theta_jn) * psi (polarisation-phase):
            # makes the likelihood-constrained polarisation/phase combination an
            # explicit flow axis.  ``psi`` (angle-pi) and ``theta_jn``
            # (angle-sine) are prerequisites.
            reps[name] = {"reparameterisation": "polarisation-phase"}
    return reps


#: Dummy prior bounds for the throwaway reparameterisation build in
#: :func:`_prime_parameter_names`.  Values are irrelevant; each just has to be a
#: finite range valid for that parameter's reparameterisation.
_DUMMY_PRIOR_BOUNDS = {
    "ra": (0.0, _TWO_PI),
    "dec": (-np.pi / 2, np.pi / 2),
    "theta_jn": (0.0, np.pi),
    "iota": (0.0, np.pi),
    "tilt_1": (0.0, np.pi),
    "tilt_2": (0.0, np.pi),
    "psi": (0.0, np.pi),
    # ``phase`` bounds also serve the derived ``delta_phase`` coordinate
    # (``polarisation-phase``), which needs no entry of its own.
    "phase": (0.0, _TWO_PI),
    "phi_12": (0.0, _TWO_PI),
    "phi_jl": (0.0, _TWO_PI),
    "a_1": (0.0, 0.99),
    "a_2": (0.0, 0.99),
    "chi_1": (-0.99, 0.99),
    "chi_2": (-0.99, 0.99),
    "luminosity_distance": (10.0, 5000.0),
    "chirp_mass": (1.0, 2.0),
    "mass_ratio": (0.125, 1.0),
    "mass_1": (1.0, 3.0),
    "mass_2": (1.0, 3.0),
    "lambda_1": (0.0, 2500.0),
    "lambda_2": (0.0, 2500.0),
}


def _prime_parameter_names(
    sampling_parameters, reference_time, vertex=None, sky_2d=False,
    psi_single=False,
):
    """Prime-parameter names *and order* nessai produces for this wiring.

    Computed by configuring a throwaway
    :class:`nessai_gw.proposals.GWFlowProposal` with the same
    reparameterisation dict / fallback the real proposal uses and reading back
    ``prime_parameters``.  The order matters: the group-mixture wrapper builds
    its base-flow ``point_dict`` from ``param_names`` before
    :meth:`TriangularGroupFlowProposal.initialise` re-binds to the live
    ``prime_parameters``.

    Falls back to a name-order heuristic (right count, order not guaranteed) if
    the throwaway build fails.
    """
    names = list(sampling_parameters)

    try:
        from nessai.model import Model

        from .proposals import GWFlowProposal

        bounds = {
            name: np.asarray(
                _DUMMY_PRIOR_BOUNDS.get(name, (0.0, 1.0)), dtype=float
            )
            for name in names
        }

        class _StubModel(Model):
            def __init__(self):
                self.names = list(names)
                self.bounds = bounds

            def log_prior(self, x):
                return np.zeros(len(np.atleast_1d(x)))

            def log_likelihood(self, x):
                return np.zeros(len(np.atleast_1d(x)))

        probe = GWFlowProposal(
            _StubModel(),
            poolsize=100,
            reparameterisations=triangular_group_reparameterisations(
                names, reference_time, vertex=vertex
            ),
            fallback_reparameterisation="zscore",
        )
        probe.set_rescaling()
        prime = list(probe.prime_parameters)
        if prime:
            if sky_2d:
                # The probe builds the 3-coordinate ``sky-ra-dec`` AnglePair
                # (it has no knowledge of the group proposal's EqualAreaSky
                # override); swap the triple for the 2-coordinate names in
                # place so the pre-bind placeholder has the right count/order.
                prime = _swap_sky_triple_for_pair(prime)
            if psi_single and "psi_x" in prime and "psi_y" in prime:
                i = prime.index("psi_x")
                prime = prime[:i] + ["psi_prime"] + [
                    n for n in prime[i:] if n not in ("psi_x", "psi_y")
                ]
            return prime
    except Exception as exc:  # pragma: no cover - defensive
        import warnings

        warnings.warn(
            "Could not probe nessai for the real prime-parameter order "
            f"({exc!r}); falling back to a name-order heuristic. Buffers are "
            "re-bound at initialise, so only the pre-bind placeholder is "
            "affected.",
            RuntimeWarning,
        )

    out = []
    if "ra" in names and "dec" in names:
        out += ["sky_u", "sky_v"] if sky_2d else [
            "ra_dec_x", "ra_dec_y", "ra_dec_z"
        ]
    for name in names:
        if name in ("ra", "dec"):
            continue
        if name == "phase":
            # the group wiring carries ``phase`` as the single ``delta_phase``
            # polarisation-phase coordinate (no ``_x``/``_y`` pair, no suffix)
            out.append("delta_phase")
        elif name == "geocent_time":
            # detector-center-time: single ``t_det`` coordinate (no suffix)
            out.append("t_det")
        elif name in _ANGLE_SCALE:
            out += (
                [f"{name}_prime"]
                if (psi_single and name == "psi")
                else [f"{name}_x", f"{name}_y"]
            )
        else:
            out.append(f"{name}_prime")
    return out


def _swap_sky_triple_for_pair(prime):
    """Replace ``ra_dec_{x,y,z}`` (or ``dec_ra_*``) with ``sky_u, sky_v``."""
    for prefix in ("ra_dec", "dec_ra"):
        trip = [f"{prefix}_{c}" for c in ("x", "y", "z")]
        if all(t in prime for t in trip):
            i = prime.index(trip[0])
            return prime[:i] + ["sky_u", "sky_v"] + [
                n for n in prime[i:] if n not in trip
            ]
    return prime


def recommended_sky_azimuth_offset(action, ra, dec):
    """Fold ``(ra, dec)`` to the fundamental domain and report its azimuth.

    Returns a dict with

    * ``concentration`` -- 0 (folded azimuth uniform on ``[0, pi/2)``) to 1
      (delta).  A recentre is only worth triggering once this is well above
      ~0.5 (the canonical sky posterior is genuinely localised).
    * ``circ_mean_lambda`` -- circular mean of the folded detector-frame
      azimuth, in ``[0, pi/2)``.
    * ``recommended_azimuth_offset`` -- the extra ``azimuth_offset`` (rad,
      taken mod ``pi/2``) that would move ``circ_mean_lambda`` to ``pi/4``,
      the centre of the fundamental wedge, so the Z4 seams sit furthest from
      the peak.  Pass it to :func:`make_et_group_flow_proposal` (added to any
      current offset) and retrain the flow from scratch.
    * ``fraction_near_seam`` -- fraction of points within 0.15 rad of a Z4
      seam under the current frame.

    ``action`` is any :class:`TriangularDetectorGroupAction`; only its
    ``sky_frame_rotation`` is used.
    """
    ra = np.asarray(ra, dtype=float)
    dec = np.asarray(dec, dtype=float)
    R = np.asarray(action.sky_frame_rotation, dtype=float)
    w_eq = np.stack(
        [np.cos(dec) * np.cos(ra), np.cos(dec) * np.sin(ra), np.sin(dec)],
        axis=-1,
    )
    wf = w_eq @ R.T
    # fold to the canonical +++ octant: reflect z, bring azimuth to [0, pi/2)
    x, y, z = wf[:, 0].copy(), wf[:, 1].copy(), np.abs(wf[:, 2])
    lam = np.mod(np.arctan2(y, x), 2 * np.pi)
    k = np.floor(lam / (0.5 * np.pi))
    ang = -k * (0.5 * np.pi)
    xr = np.cos(ang) * x - np.sin(ang) * y
    yr = np.sin(ang) * x + np.cos(ang) * y
    lam_f = np.mod(np.arctan2(yr, xr), 0.5 * np.pi)
    z4 = np.mean(np.exp(4j * lam_f))
    circ_mean = np.mod(np.angle(z4) / 4.0, 0.5 * np.pi)
    return {
        "concentration": float(np.abs(z4)),
        "circ_mean_lambda": float(circ_mean),
        "recommended_azimuth_offset": float(
            np.mod(circ_mean - 0.25 * np.pi, 0.5 * np.pi)
        ),
        "fraction_near_seam": float(
            np.mean((lam_f < 0.15) | (lam_f > 0.5 * np.pi - 0.15))
        ),
        "n": int(ra.size),
    }


def make_triangular_group_flow_proposal(
    sampling_parameters,
    reference_time,
    plane_normal,
    vertex,
    prime_space=True,
    phase_reflection=False,
    azimuth_offset=0.0,
    boundary_reflection=False,
    sky_radial_sigma=0.15,
    gaussianise_sky="auto",
    sky_2d="auto",
    psi_single=True,
    polarisation_quarter=True,
    n_clusters_max=1,
    cluster_method="gmm",
    cluster_max_overlap=0.05,
    cluster_min_size=200,
):
    """Build a ``FlowProposal`` subclass wired for the triangular-detector group mixture.

    The returned class combines :class:`nessai_gw.proposals.GWReparamMixin`
    (GW reparameterisations by parameter name),
    :class:`nessai.flowmodel.group_mixture.GroupFlowProposalMixin` (group-mixture
    wiring) and :class:`nessai.proposal.FlowProposal`, with
    :class:`TriangularDetectorGroupAction` as the group action.  Pass it as
    ``flow_proposal_class`` to ``bilby.run_sampler(sampler="nessai", ...)``
    together with :func:`triangular_group_reparameterisations`.

    Parameters
    ----------
    sampling_parameters : list of str
        Every parameter nessai samples, in order.  Must contain ``ra``, ``dec``,
        ``theta_jn``, ``psi``, ``phase`` and ``geocent_time``.
    reference_time : float
        Geocentric GPS time of the event.
    plane_normal : array_like
        Earth-fixed unit normal to the detector plane.
    vertex : array_like
        Geocentric detector position (metres).
    prime_space : bool, optional
        If ``True`` (default) run the action in the flow's prime space via
        :class:`PrimeSpaceTriangularGroupAction` (exact unit Jacobian, no
        per-call numpy round-trip).  If ``False`` run it in physical coordinates
        and let nessai's ``GroupFlowProposalMixin`` bridge to prime space with a
        ``ReparamBridge``.
    phase_reflection : bool, optional
        Fold in the extra ``phase -> phase + pi`` (2, 2)-mode degeneracy
        (16-element group).  See :class:`TriangularDetectorGroupAction`.
    azimuth_offset : float, optional
        In-plane rotation (rad) of the detector frame about the plane normal,
        moving the Z4 fundamental-domain seams off the sky-posterior peak.
        Use :func:`recommended_sky_azimuth_offset` on a localised run to pick
        it, then retrain from scratch.  Default ``0.0``.
    boundary_reflection : bool, optional
        Only on the prime-space path.  Symmetrise the base flow across the
        ``ra_dec_{x,y,z} = 0`` octant faces so it need not model the wall
        cliffs (see ``reflect_parameters`` in
        :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow`).
        Default ``False``.
    sky_radial_sigma : float or None, optional
        Width of the auxiliary sky radial coordinate (see
        :class:`~nessai_gw.reparameterisations.sky.RotatedAnglePair`).  The
        default (``0.15``) confines the sky prime points to a thin unit shell
        so the base flow never has to taper a cone into the ``r = 0``
        coordinate singularity; ``None`` restores ``AnglePair``'s ``chi(3)``.
    gaussianise_sky : bool or "auto", optional
        Only on the prime-space path.  Install :class:`SkyOctantGaussianiser`
        as the group-mixture ``canonical_transform``: the base flow then sees
        the canonical sky octant mapped (cylindrical equal-area + probit) to
        two independent standard normals plus the pass-through radius, instead
        of the uniform-on-sphere octant with its hard prior edge.  Supersedes
        ``boundary_reflection`` for the sky (the octant walls move to
        ``+/-inf``).  Default ``"auto"`` -- on whenever ``prime_space`` is
        ``True``.  Pass ``False`` to opt out, or an explicit ``True`` with
        ``prime_space=False`` to get an error rather than a silent no-op.
    sky_2d : bool or "auto", optional
        Drop the auxiliary sky radial coordinate and carry the sky as the two
        equal-area coordinates ``(sky_u, sky_v)`` (see
        :class:`~nessai_gw.reparameterisations.sky.EqualAreaSky` +
        :class:`SkyOctantProbit`).  Default ``"auto"`` -- on whenever
        ``prime_space`` and ``gaussianise_sky`` are both active (the machinery
        it needs), off otherwise.  Requires the prime-space path.
    psi_single : bool, optional
        Carry ``psi`` as a single ``psi_prime`` coordinate
        (:class:`~nessai_gw.reparameterisations.phase.SingleAngleReparameterisation`)
        instead of the ``angle-pi`` Cartesian pair + ``chi(2)`` radius.  The
        free radius of the pair turns a well-structured ``psi`` into a
        leptokurtic origin cusp; the single coordinate is cleaner (measured
        ~1.4 nat lower non-Gaussianity on a v16 ET-Delta fold).  Default
        ``True``.
    polarisation_quarter : bool, optional
        Promote the phase sector from ``Z2`` to ``Z4`` by folding the
        ``{psi -> psi + pi/2, phase -> phase - pi/2}`` polarisation/phase
        quarter turn into the group (32 elements; forces
        ``phase_reflection``).  This makes ``psi_prime`` unimodal in the base
        frame -- the ``{psi -> psi + pi/2}`` degeneracy is otherwise left for
        the base flow to model as a second mode.  Default ``True``.
    n_clusters_max : int
        If ``> 1``, use a *clustered* base flow: up to ``n_clusters_max``
        independent group-mixture experts, one per data cluster (found each
        training round by GMM + BIC, ``k`` in ``[1, n_clusters_max]``), each
        with its own per-branch canonical standardisation and latent ball.
        ``k`` collapses to 1 -- byte identical to the single-flow behaviour --
        whenever the data is not decisively multi-modal.  Default ``1`` (off).
    cluster_method : {"gmm", "kmeans"}
        Clustering algorithm on the standardised folded base frame.
    cluster_max_overlap : float
        A ``k``-way split is accepted only if at most this fraction of points
        are ambiguous between clusters (GMM responsibility < 0.8).  Smaller =
        more conservative; ``k`` collapses to 1 when no split is clean.
    cluster_min_size : int
        Smallest allowed cluster (a split producing a smaller cluster is
        rejected).
    """
    try:
        from nessai.proposal import FlowProposal
        from nessai.flowmodel.group_mixture import (
            GroupFlowProposalMixin,
            make_group_mixture_flow,
        )
    except ImportError as exc:  # pragma: no cover - depends on nessai version
        raise RuntimeError(
            "make_triangular_group_flow_proposal requires a version of nessai "
            "that ships nessai.flowmodel.group_mixture (GroupFlowProposalMixin, "
            "make_group_mixture_flow)."
        ) from exc

    if int(n_clusters_max) > 1:
        try:
            from nessai.flowmodel.group_mixture import (
                make_clustered_group_mixture_flow,
            )
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError(
                "n_clusters_max > 1 requires a version of nessai whose "
                "nessai.flowmodel.group_mixture ships "
                "make_clustered_group_mixture_flow."
            ) from exc

        def _make_flow_model(**gm):
            return make_clustered_group_mixture_flow(
                n_clusters_max=int(n_clusters_max),
                cluster_method=cluster_method,
                max_cluster_overlap=float(cluster_max_overlap),
                min_cluster_size=int(cluster_min_size),
                **gm,
            )
    else:
        _make_flow_model = make_group_mixture_flow

    from .proposals import GWReparamMixin

    if gaussianise_sky == "auto":
        gaussianise_sky = bool(prime_space)
    elif gaussianise_sky and not prime_space:
        raise RuntimeError(
            "gaussianise_sky is only supported on the prime-space path "
            "(prime_space=True)."
        )
    if sky_2d == "auto":
        # 2-D equal-area sky (no auxiliary radial coord) whenever the
        # prime-space + gaussianise-sky machinery it needs is available.
        sky_2d = bool(prime_space) and bool(gaussianise_sky)
    if sky_2d and not prime_space:
        raise RuntimeError("sky_2d is only supported on the prime-space path.")
    if sky_2d and not gaussianise_sky:
        raise RuntimeError(
            "sky_2d needs gaussianise_sky (the SkyOctantProbit canonical "
            "transform turns the folded equal-area sub-square into N(0, 1))."
        )

    names = list(sampling_parameters)
    missing = sorted(
        {"ra", "dec", "theta_jn", "psi", "phase", "geocent_time"} - set(names)
    )
    if missing:
        raise RuntimeError(
            f"The sampling space is missing {missing}, which the triangular-detector "
            "group action needs; this proposal only applies to a single-site "
            "triangular-detector run with the standard extrinsic parameters."
        )

    base_action = TriangularDetectorGroupAction(
        reference_time=reference_time,
        plane_normal=plane_normal,
        vertex=vertex,
        phase_reflection=phase_reflection,
        azimuth_offset=azimuth_offset,
        polarisation_quarter=polarisation_quarter,
    )

    if prime_space:
        prime_names = _prime_parameter_names(
            names, reference_time, vertex=vertex, sky_2d=sky_2d,
            psi_single=psi_single,
        )
        action = PrimeSpaceTriangularGroupAction(base_action, prime_names)
        gm_kwargs = {}
        import inspect as _inspect

        _gm_params = _inspect.signature(make_group_mixture_flow).parameters
        if gaussianise_sky:
            if "canonical_transform" not in _gm_params:
                raise RuntimeError(
                    "gaussianise_sky requires a version of nessai whose "
                    "make_group_mixture_flow accepts `canonical_transform`."
                )
            gm_kwargs["canonical_transform"] = (
                SkyOctantProbit(prime_names)
                if sky_2d
                else SkyOctantGaussianiser(prime_names)
            )
            if boundary_reflection:
                logger.warning(
                    "gaussianise_sky pushes the octant walls to +/-inf; "
                    "ignoring boundary_reflection for the sky coordinates."
                )
                boundary_reflection = False
        if boundary_reflection:
            if "reflect_parameters" not in _gm_params:
                raise RuntimeError(
                    "boundary_reflection requires a version of nessai whose "
                    "make_group_mixture_flow accepts `reflect_parameters`."
                )
            gm_kwargs["reflect_parameters"] = [
                p
                for p in ("ra_dec_x", "ra_dec_y", "ra_dec_z")
                if p in prime_names
            ]
        flow_model_cls = _make_flow_model(
            group_action_fn=action,  # ignored on the prime-space path
            group_size=base_action.group_size,
            param_names=prime_names,
            prime_space_action=action,
            prime_space_in_domain=action.in_fundamental_domain,
            min_canon_std=_MIN_CANON_STD,
            **gm_kwargs,
        )
    else:
        action = None
        flow_model_cls = _make_flow_model(
            group_action_fn=base_action,
            group_size=base_action.group_size,
            param_names=base_action.parameters,
            in_fundamental_domain=base_action.in_fundamental_domain,
            min_canon_std=_MIN_CANON_STD,
        )

    class TriangularGroupFlowProposal(
        GWReparamMixin, GroupFlowProposalMixin, FlowProposal
    ):
        """``FlowProposal`` wired for the triangular-detector group-mixture flow
        with the nessai-gw GW reparameterisations."""

        _FlowModelClass = flow_model_cls

        def add_default_reparameterisations(self):
            # Sky: use the detector-frame-rotated AnglePair so the group's
            # fundamental domain is the axis-aligned octant x, y, z >= 0
            # rather than an oblique equatorial wedge (see RotatedAnglePair).
            rep = self._reparameterisation
            model_names = set(self.model.names)
            if psi_single and "psi" in model_names and "psi" not in set(
                rep.parameters
            ):
                # Single ``psi_prime`` coordinate instead of the angle-pi
                # Cartesian pair + chi(2) radius (the bare psi is only weakly
                # constrained; the pair's free radius gives an origin cusp).
                from .reparameterisations.phase import (
                    SingleAngleReparameterisation,
                )

                rep.add_reparameterisation(
                    SingleAngleReparameterisation(
                        parameters=["psi"],
                        prior_bounds={"psi": self.model.bounds["psi"]},
                        scale=2.0,
                    )
                )
            if {"ra", "dec"} <= model_names and not (
                {"ra", "dec"} & set(rep.parameters)
            ):
                sky_bounds = {
                    k: self.model.bounds[k] for k in ("ra", "dec")
                }
                if sky_2d:
                    from .reparameterisations.sky import EqualAreaSky

                    rep.add_reparameterisation(
                        EqualAreaSky(
                            parameters=["ra", "dec"],
                            prior_bounds=sky_bounds,
                            rotation=base_action.sky_frame_rotation,
                            rng=self.rng,
                        )
                    )
                else:
                    from .reparameterisations.sky import RotatedAnglePair

                    rep.add_reparameterisation(
                        RotatedAnglePair(
                            parameters=["ra", "dec"],
                            prior_bounds=sky_bounds,
                            convention="ra-dec",
                            rotation=base_action.sky_frame_rotation,
                            radial_sigma=sky_radial_sigma,
                            rng=self.rng,
                        )
                    )
            super().add_default_reparameterisations()

        def initialise(self, *args, **kwargs):
            super().initialise(*args, **kwargs)
            if action is None:
                return
            # Realign the prime-space action to nessai's actual prime parameter
            # order (do not assume the reparameterisation-dict order).
            model = getattr(self.flow, "model", None)
            prime = list(getattr(self, "prime_parameters", []) or [])
            if model is not None and prime:
                action.bind(prime)
                if hasattr(model, "set_param_names"):
                    model.set_param_names(prime)
                else:
                    model.param_names = prime

        def train(self, x, **kwargs):
            out = super().train(x, **kwargs)
            try:
                names = getattr(getattr(x, "dtype", None), "names", None) or ()
                if "ra" in names and "dec" in names:
                    d = recommended_sky_azimuth_offset(
                        base_action, x["ra"], x["dec"]
                    )
                    logger.debug(
                        "[sky] folded-azimuth concentration %.3f, circ-mean "
                        "%.3f rad; current azimuth_offset %.4f, recommended "
                        "extra offset %.4f rad (%.1f deg); %.1f%% of points "
                        "near a Z4 seam. %s",
                        d["concentration"],
                        d["circ_mean_lambda"],
                        base_action.azimuth_offset,
                        d["recommended_azimuth_offset"],
                        np.degrees(d["recommended_azimuth_offset"]),
                        100 * d["fraction_near_seam"],
                        (
                            "Well localised -- a recentre + full retrain is "
                            "worthwhile."
                            if d["concentration"] > 0.5
                            else "Not localised enough to recentre yet."
                        ),
                    )
            except Exception as exc:  # pragma: no cover - diagnostic only
                logger.debug("sky azimuth diagnostic failed: %s", exc)
            return out

    # nessai checkpoints the sampler (hence the proposal *instance*) with
    # ``pickle``, which resolves an instance's class by ``module.__qualname__``.
    # Publish this otherwise-local class at module scope under a stable name.
    TriangularGroupFlowProposal.__module__ = __name__
    TriangularGroupFlowProposal.__qualname__ = "TriangularGroupFlowProposal"
    globals()["TriangularGroupFlowProposal"] = TriangularGroupFlowProposal
    return TriangularGroupFlowProposal


# ---------------------------------------------------------------------------
# Einstein Telescope (ET-EMR / Meuse-Rhine site) specifics
#
# Everything above is detector-agnostic.  The ET layer is just the two Earth-fixed
# numbers -- the detector-plane normal and the vertex position -- plus thin
# subclass / factory wrappers that fill them in.
# ---------------------------------------------------------------------------

#: Geocentric position (metres, Earth-fixed frame) of the ``ET-EMR`` site,
#: WGS84 geodetic ``(lat, lon, height) = (50 deg 43' 23", 5 deg 55' 14", 0)``.
#: Recompute with :func:`detector_vertex` (or
#: :func:`detector_vertex_from_geodetic`) for a different geometry.
ET_EMR_VERTEX = np.array(
    [4024345.21150611, 417334.87759012, 4914098.18878217]
)

#: Unit normal to the ET-EMR detector plane in the Earth-fixed (geocentric)
#: frame, ``mean_i normalise(x_arm_i x y_arm_i)`` for the three nested
#: interferometers of the ``ET-EMR`` triangle shipped with ``bilby_xG``
#: (Meuse-Rhine site, lat 50 deg 43' 23", lon 5 deg 55' 14").  Recompute with
#: :func:`detector_plane_normal` for a different geometry.
ET_EMR_PLANE_NORMAL = np.array(
    [0.6290179004039584, 0.06512521686797399, 0.7746581091603363]
)


class ETTriangleGroupAction(TriangularDetectorGroupAction):
    """:class:`TriangularDetectorGroupAction` with the ET-EMR geometry.

    A thin subclass: ``plane_normal`` / ``vertex`` default to
    :data:`ET_EMR_PLANE_NORMAL` / :data:`ET_EMR_VERTEX` (pass explicit values,
    e.g. from :func:`detector_plane_normal` / :func:`detector_vertex` on a bilby
    ``InterferometerList(["ET"])``, to override).  All the behaviour lives in the
    base class.
    """

    def __init__(
        self,
        reference_time,
        plane_normal=None,
        vertex=None,
        phase_reflection=False,
        azimuth_offset=0.0,
        polarisation_quarter=False,
    ):
        super().__init__(
            reference_time,
            plane_normal=(
                ET_EMR_PLANE_NORMAL if plane_normal is None else plane_normal
            ),
            vertex=ET_EMR_VERTEX if vertex is None else vertex,
            phase_reflection=phase_reflection,
            azimuth_offset=azimuth_offset,
            polarisation_quarter=polarisation_quarter,
        )


def make_et_triangle_group_mixture_flow(
    reference_time,
    plane_normal=None,
    vertex=None,
    parameters=None,
    phase_reflection=False,
    azimuth_offset=0.0,
):
    """:func:`make_triangular_group_mixture_flow` with the ET-EMR geometry."""
    return make_triangular_group_mixture_flow(
        reference_time,
        plane_normal=(
            ET_EMR_PLANE_NORMAL if plane_normal is None else plane_normal
        ),
        vertex=ET_EMR_VERTEX if vertex is None else vertex,
        parameters=parameters,
        phase_reflection=phase_reflection,
        azimuth_offset=azimuth_offset,
    )


def make_et_group_flow_proposal(
    sampling_parameters,
    reference_time,
    plane_normal=None,
    vertex=None,
    prime_space=True,
    phase_reflection=False,
    azimuth_offset=0.0,
    boundary_reflection=False,
    sky_radial_sigma=0.15,
    gaussianise_sky="auto",
    sky_2d="auto",
    psi_single=True,
    polarisation_quarter=True,
    n_clusters_max=1,
    cluster_method="gmm",
    cluster_max_overlap=0.05,
    cluster_min_size=200,
):
    """:func:`make_triangular_group_flow_proposal` with the ET-EMR geometry."""
    return make_triangular_group_flow_proposal(
        sampling_parameters,
        reference_time,
        plane_normal=(
            ET_EMR_PLANE_NORMAL if plane_normal is None else plane_normal
        ),
        vertex=ET_EMR_VERTEX if vertex is None else vertex,
        prime_space=prime_space,
        phase_reflection=phase_reflection,
        azimuth_offset=azimuth_offset,
        boundary_reflection=boundary_reflection,
        gaussianise_sky=gaussianise_sky,
        sky_radial_sigma=sky_radial_sigma,
        sky_2d=sky_2d,
        psi_single=psi_single,
        polarisation_quarter=polarisation_quarter,
        n_clusters_max=n_clusters_max,
        cluster_method=cluster_method,
        cluster_max_overlap=cluster_max_overlap,
        cluster_min_size=cluster_min_size,
    )
