"""Discrete symmetry transformations for the triangular Einstein Telescope.

nessai's :mod:`nessai.flowmodel.group_mixture` can learn a discrete mixture
over a finite symmetry group that acts on the (physical) parameters, letting
the normalising flow model a single mode while the mixture accounts for the
others.  This module provides the group for a single triangular detector such
as one Einstein Telescope (ET) site.

In the long-wavelength / "frozen" limit the extrinsic likelihood of a single
triangular detector is invariant under an eight-element group.  This is the
exact analogue of the LISA sky-mode degeneracy summarised in Table III (and
Eqs. 63-65) of

    S. Marsat, J. G. Baker and T. Dal Canton,
    "Exploring the Bayesian parameter estimation of binary black holes with
    LISA", Phys. Rev. D 103, 083011 (2021) [arXiv:2003.00357].

Writing ``(lambda, beta, psi)`` for the source azimuth, elevation and
polarisation *in the detector-plane frame* and ``iota`` for the inclination,
the group is generated by

* a rotation of the source azimuth by ``pi / 2`` about the detector normal,
  compensated by a ``pi / 2`` shift of the polarisation (Eq. 64)::

      lambda -> lambda + k pi / 2   (k = 0, 1, 2, 3)
      psi    -> psi    + k pi / 2

  (the ``m = +-2`` pattern functions pick up an overall sign under a
  quarter turn, which the polarisation shift undoes); and

* a reflection of the source through the detector plane (Eq. 63)::

      beta -> -beta,   psi -> pi - psi,   iota -> pi - iota

  (reflecting ``beta`` swaps ``F_+`` for a ``psi``-flipped response and
  flips the sign of ``F_x``, which ``iota -> pi - iota`` compensates for the
  dominant quadrupole).

The reference phase ``phase`` is unchanged by every element.  The four
rotations and the two reflection states give ``4 x 2 = 8`` elements; the
group is :math:`\\mathbb{Z}_4 \\times \\mathbb{Z}_2` (abelian).

Unlike LISA, a ground-based triangle sits at an appreciable offset
``r_ET`` from the geocenter, so the sky degeneracy is only a degeneracy of
the *detector-frame* arrival time, not of the geocentric time ``geocent_time``
that bilby samples.  With ``n`` the unit vector towards the source,

    geocent_time = t_det + (n . r_ET) / c

(Eq. 22 of Santoliquido et al. 2025, arXiv:2504.21087), so every element of
the group -- and in particular the plane reflection, which sends
``n . r_ET -> -n . r_ET`` for a near-radial site and thus produces the
bimodal ``geocent_time`` posterior of that paper -- must carry
``geocent_time`` along by the change in the geocenter-to-detector delay::

    geocent_time -> geocent_time + delay(n) - delay(n')

where ``n'`` is the transformed source direction and
``delay(n) = -(n . r_ET) / c`` is bilby's ``time_delay_from_geocenter``.  This is an additive shift
that depends only on the (already transformed) sky position, so it leaves the
Jacobian of the whole action equal to one.

The transformations act on the *geocentric* parameters used by bilby, but in
the measure-preserving coordinates ``ra``, ``sin_dec`` (``= sin(dec)``),
``cos_theta_jn`` (``= cos(theta_jn)``), ``psi``, ``phase`` and
``geocent_time``.  The sky
rotations/reflection are isometries of the sphere, so they preserve
``d(ra) d(sin_dec)``; the reflection sends ``cos_theta_jn -> -cos_theta_jn``;
and ``psi`` only picks up constant shifts and a sign flip.  The whole action
therefore has unit Jacobian in these coordinates -- which is what
:class:`nessai.flowmodel.group_mixture.DiscreteGroupMixtureFlowWrapper`
assumes (it treats the action as measure-preserving).  In the raw angles
``dec`` / ``theta_jn`` it would *not* be, and the omitted ``cos(dec)`` /
``sin(theta_jn)`` factors wreck the importance weights.

Points are carried into the detector-plane frame, transformed there, and
carried back, using exactly bilby's polarisation-tensor convention (Nishizawa
et al. 2009), so a transformed point reproduces the antenna response of the
original one.
"""

from __future__ import annotations

import numpy as np
import torch

from . import nessai_logger

logger = nessai_logger.getChild(__name__)

#: Parameters the group acts on, in the order expected by the flow.  These
#: are the *measure-preserving* coordinates: ``sin_dec = sin(dec)`` and
#: ``cos_theta_jn = cos(theta_jn)`` rather than the raw angles, so the action
#: has unit Jacobian (see the module docstring).
ET_TRIANGLE_PARAMETERS = [
    "ra",
    "sin_dec",
    "cos_theta_jn",
    "psi",
    "phase",
    "geocent_time",
]

#: Number of group elements.
ET_TRIANGLE_GROUP_SIZE = 8

#: Speed of light in m / s (CODATA / bilby ``speed_of_light``).
_SPEED_OF_LIGHT = 299792458.0

#: Geocentric position (metres, Earth-fixed frame) of the ``ET-EMR`` site,
#: WGS84 geodetic ``(lat, lon, height) = (50 deg 43' 23", 5 deg 55' 14", 0)``.
#: Used to convert between the detector-frame arrival time and bilby's
#: ``geocent_time``.  Recompute with :func:`detector_vertex` for a different
#: geometry.
ET_EMR_VERTEX = np.array(
    [4024345.21150611, 417334.87759012, 4914098.18878217]
)

#: Unit normal to the ET-EMR detector plane in the Earth-fixed (geocentric)
#: frame, ``mean_i normalise(x_arm_i x y_arm_i)`` for the three nested
#: interferometers of the ``ET-EMR`` triangle shipped with ``bilby_xG``
#: (Meuse-Rhine site, lat 50 deg 43' 23", lon 5 deg 55' 14").  Recompute with
#: :func:`detector_plane_normal` for a different geometry.
ET_EMR_PLANE_NORMAL = np.array(
    [0.6290179004039584, 0.06512521686797399, 0.7746581091603363]
)

_TWO_PI = 2.0 * np.pi


def detector_plane_normal(interferometers) -> np.ndarray:
    """Unit normal to the plane of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects (the three
        nested detectors of the triangle), each exposing ``geometry.x`` and
        ``geometry.y`` unit arm vectors in the Earth-fixed frame.

    Returns
    -------
    numpy.ndarray
        The mean arm-plane normal, normalised to unit length.
    """
    normals = []
    for ifo in interferometers:
        x = np.asarray(ifo.geometry.x, dtype=float)
        y = np.asarray(ifo.geometry.y, dtype=float)
        n = np.cross(x, y)
        normals.append(n / np.linalg.norm(n))
    n = np.mean(normals, axis=0)
    return n / np.linalg.norm(n)


def detector_vertex(interferometers) -> np.ndarray:
    """Mean geocentric vertex position (metres) of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects, each exposing
        ``geometry.vertex`` (its Earth-fixed position in metres).

    Returns
    -------
    numpy.ndarray
        The mean of the three vertex positions.
    """
    vertices = [
        np.asarray(ifo.geometry.vertex, dtype=float) for ifo in interferometers
    ]
    return np.mean(vertices, axis=0)


def detector_vertex_from_geodetic(
    latitude: float, longitude: float, height: float = 0.0
) -> np.ndarray:
    """Earth-fixed position (metres) from WGS84 geodetic coordinates.

    Parameters
    ----------
    latitude, longitude : float
        Geodetic latitude and longitude in radians.
    height : float, optional
        Height above the WGS84 ellipsoid in metres (default 0).
    """
    a = 6378137.0
    f = 1.0 / 298.257223563
    e2 = f * (2.0 - f)
    sin_lat = np.sin(latitude)
    n = a / np.sqrt(1.0 - e2 * sin_lat**2)
    return np.array(
        [
            (n + height) * np.cos(latitude) * np.cos(longitude),
            (n + height) * np.cos(latitude) * np.sin(longitude),
            (n * (1.0 - e2) + height) * sin_lat,
        ]
    )


def _greenwich_mean_sidereal_time(gps_time: float) -> float:
    """GMST in radians at ``gps_time`` (via bilby if it is available)."""
    try:
        from bilby_cython.time import greenwich_mean_sidereal_time

        return float(greenwich_mean_sidereal_time(gps_time)) % _TWO_PI
    except Exception:  # pragma: no cover - fallback only
        # IAU 1982 GMST, adequate (<~1 arcmin) for a discrete-mode proposal.
        jd = gps_time / 86400.0 + 2444244.5
        t = (jd - 2451545.0) / 36525.0
        gmst_seconds = (
            67310.54841
            + (876600.0 * 3600.0 + 8640184.812866) * t
            + 0.093104 * t**2
            - 6.2e-6 * t**3
        )
        return (gmst_seconds * np.pi / 43200.0) % _TWO_PI


def _detector_frame_basis(plane_normal: np.ndarray) -> np.ndarray:
    """Orthonormal Earth-fixed basis ``[e1, e2, e3]`` with ``e3`` the normal.

    ``e1`` is the (Earth-fixed) z-axis projected into the plane.  The choice
    of in-plane axes only shifts ``lambda`` and ``psi`` by a constant, which
    the group action is equivariant under, so it does not matter.
    """
    e3 = np.asarray(plane_normal, dtype=float)
    e3 = e3 / np.linalg.norm(e3)
    e1 = np.array([0.0, 0.0, 1.0]) - e3[2] * e3
    e1 = e1 / np.linalg.norm(e1)
    e2 = np.cross(e3, e1)
    return np.stack([e1, e2, e3])


def _uvw(phi: torch.Tensor, theta: torch.Tensor):
    """bilby (Nishizawa 2009) frame vectors for colatitude/azimuth angles."""
    cp, sp = torch.cos(phi), torch.sin(phi)
    ct, st = torch.cos(theta), torch.sin(theta)
    zero = torch.zeros_like(phi)
    u = torch.stack([cp * ct, ct * sp, -st], dim=-1)
    v = torch.stack([-sp, cp, zero], dim=-1)
    w = torch.stack([st * cp, st * sp, ct], dim=-1)
    return u, v, w


def _polarisation_angle(m: torch.Tensor, u: torch.Tensor, v: torch.Tensor):
    """Recover ``psi`` from ``m``, where ``m = -u sin psi - v cos psi``."""
    return torch.atan2(-(m * u).sum(-1), -(m * v).sum(-1))


class ETTriangleGroupAction:
    """Callable eight-element group action for a triangular detector.

    Instances are the ``group_action_fn`` /  ``in_fundamental_domain`` pair
    consumed by :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event.  Only the Greenwich mean sidereal
        time it implies is used (to rotate between the equatorial and
        Earth-fixed frames); the ~tens-of-ms spread of a posterior is
        negligible here.
    plane_normal : array_like, optional
        Unit normal to the detector plane in the Earth-fixed frame.  Defaults
        to :data:`ET_EMR_PLANE_NORMAL`.  Use :func:`detector_plane_normal` to
        build one from a bilby interferometer list.
    vertex : array_like, optional
        Geocentric position of the detector (metres, Earth-fixed frame), used
        to carry ``geocent_time`` along with the sky transformation.  Defaults
        to :data:`ET_EMR_VERTEX`.  Use :func:`detector_vertex` to build one
        from a bilby interferometer list.
    """

    parameters = ET_TRIANGLE_PARAMETERS
    group_size = ET_TRIANGLE_GROUP_SIZE

    def __init__(self, reference_time, plane_normal=None, vertex=None):
        self.reference_time = float(reference_time)
        self.gmst = _greenwich_mean_sidereal_time(self.reference_time)
        if plane_normal is None:
            plane_normal = ET_EMR_PLANE_NORMAL
        self.plane_normal = np.asarray(plane_normal, dtype=float)
        self._basis_np = _detector_frame_basis(self.plane_normal)
        self._basis = torch.as_tensor(self._basis_np, dtype=torch.float64)
        if vertex is None:
            vertex = ET_EMR_VERTEX
        self.vertex = np.asarray(vertex, dtype=float)
        self._vertex = torch.as_tensor(self.vertex, dtype=torch.float64)

    # -- coordinate maps ------------------------------------------------

    def _to_frame(self, ra, dec, psi):
        """Equatorial ``(ra, dec, psi)`` -> detector-frame angles."""
        basis = self._basis.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        u, v, w = _uvw(phi, theta)
        m = -u * torch.sin(psi)[..., None] - v * torch.cos(psi)[..., None]
        w_f = w @ basis.T
        m_f = m @ basis.T
        theta_f = torch.acos(torch.clamp(w_f[..., 2], -1.0, 1.0))
        lam_f = torch.atan2(w_f[..., 1], w_f[..., 0])
        u_f, v_f, _ = _uvw(lam_f, theta_f)
        psi_f = _polarisation_angle(m_f, u_f, v_f)
        beta_f = 0.5 * np.pi - theta_f
        return lam_f, beta_f, psi_f

    def _from_frame(self, lam_f, beta_f, psi_f):
        """Detector-frame angles -> equatorial ``(ra, dec, psi)``."""
        basis = self._basis.to(lam_f.dtype)
        theta_f = 0.5 * np.pi - beta_f
        u_f, v_f, w_f = _uvw(lam_f, theta_f)
        sin_psi = torch.sin(psi_f)[..., None]
        cos_psi = torch.cos(psi_f)[..., None]
        m_f = -u_f * sin_psi - v_f * cos_psi
        w = w_f @ basis
        m = m_f @ basis
        dec = torch.asin(torch.clamp(w[..., 2], -1.0, 1.0))
        phi = torch.atan2(w[..., 1], w[..., 0])
        ra = torch.remainder(phi + self.gmst, _TWO_PI)
        u, v, _ = _uvw(ra - self.gmst, 0.5 * np.pi - dec)
        psi = torch.remainder(_polarisation_angle(m, u, v), np.pi)
        return ra, dec, psi

    def _geocenter_delay(self, ra, dec):
        """Geocenter-to-detector light-travel delay ``t_det - geocent_time``.

        Equal to ``-(n . r_ET) / c`` with ``n`` the unit vector towards the
        source, matching bilby's ``time_delay_from_geocenter`` convention.
        """
        vertex = self._vertex.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        st = torch.sin(theta)
        n = torch.stack(
            [st * torch.cos(phi), st * torch.sin(phi), torch.cos(theta)],
            dim=-1,
        )
        return -(n * vertex).sum(-1) / _SPEED_OF_LIGHT

    # -- group action -------------------------------------------------

    @staticmethod
    def _decode(modes: torch.Tensor):
        """Split a mode index in ``0..7`` into ``(k, reflected)``."""
        k = torch.remainder(modes, 4).to(torch.float64)
        reflected = (torch.div(modes, 4, rounding_mode="floor") == 1)
        return k, reflected

    @staticmethod
    def _invert_modes(modes: torch.Tensor) -> torch.Tensor:
        """Index of the inverse element (the group is abelian)."""
        k = torch.remainder(modes, 4)
        refl = torch.div(modes, 4, rounding_mode="floor")
        return refl * 4 + torch.remainder(-k, 4)

    def __call__(self, point_dict: dict, modes, inverse: bool = False) -> dict:
        """Apply the group element ``modes`` (or its inverse) to each point."""
        ra = point_dict["ra"]
        sin_dec = point_dict["sin_dec"]
        psi = point_dict["psi"]
        cos_theta_jn = point_dict["cos_theta_jn"]
        phase = point_dict["phase"]
        geocent_time = point_dict["geocent_time"]

        dec = torch.asin(torch.clamp(sin_dec, -1.0, 1.0))

        modes = torch.as_tensor(modes, device=ra.device)
        if inverse:
            modes = self._invert_modes(modes)
        k, reflected = self._decode(modes)
        k = k.to(ra.dtype)
        quarter = 0.5 * np.pi * k

        lam_f, beta_f, psi_f = self._to_frame(ra, dec, psi)

        lam_f = lam_f + quarter
        beta_f = torch.where(reflected, -beta_f, beta_f)
        psi_f = torch.where(reflected, np.pi - psi_f, psi_f) + quarter
        # theta_jn -> pi - theta_jn under a reflection, i.e. a sign flip of
        # cos(theta_jn) -- unit Jacobian in this coordinate.
        cos_theta_jn = torch.where(
            reflected, -cos_theta_jn, cos_theta_jn
        )

        ra_t, dec_t, psi_t = self._from_frame(lam_f, beta_f, psi_f)

        # The sky degeneracy fixes the detector-frame arrival time, not the
        # geocentric one: shift geocent_time by the change in the
        # geocenter-to-detector delay (Santoliquido et al. 2025, Eq. 22).
        geocent_time_t = (
            geocent_time
            + self._geocenter_delay(ra, dec)
            - self._geocenter_delay(ra_t, dec_t)
        )

        return {
            "ra": ra_t,
            "sin_dec": torch.sin(dec_t),
            "cos_theta_jn": cos_theta_jn,
            "psi": psi_t,
            "phase": phase,
            "geocent_time": geocent_time_t,
        }

    def in_fundamental_domain(self, point_dict: dict) -> torch.Tensor:
        """Boolean mask: is each point the canonical point of its orbit?

        The canonical point is the one whose detector-frame azimuth lies in
        ``[0, pi / 2)`` and which sits on the ``beta >= 0`` side of the
        detector plane -- exactly one of the eight images of a generic point.
        """
        dec = torch.asin(torch.clamp(point_dict["sin_dec"], -1.0, 1.0))
        lam_f, beta_f, _ = self._to_frame(
            point_dict["ra"], dec, point_dict["psi"]
        )
        in_quarter = torch.remainder(lam_f, _TWO_PI) < 0.5 * np.pi
        return in_quarter & (beta_f >= 0.0)


def make_et_triangle_group_mixture_flow(
    reference_time, plane_normal=None, vertex=None, parameters=None
):
    """Build a group-mixture ``FlowModel`` class for a triangular detector.

    Thin wrapper around
    :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow` bound to
    :class:`ETTriangleGroupAction`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event (see :class:`ETTriangleGroupAction`).
    plane_normal : array_like, optional
        Earth-fixed unit normal to the detector plane; defaults to
        :data:`ET_EMR_PLANE_NORMAL`.
    vertex : array_like, optional
        Geocentric detector position (metres); defaults to
        :data:`ET_EMR_VERTEX`.
    parameters : list of str, optional
        Override the acted-on parameter names/order (default
        :data:`ET_TRIANGLE_PARAMETERS`).  The flow must be given exactly
        these inputs, in this order.

    Returns
    -------
    type
        A ``GroupMixtureFlowModel`` subclass, suitable as ``_FlowModelClass``
        of a :class:`nessai.flowmodel.group_mixture.GroupFlowProposal` (or the
        ``flow_class`` of a flow config).
    """
    from nessai.flowmodel.group_mixture import make_group_mixture_flow

    action = ETTriangleGroupAction(
        reference_time=reference_time,
        plane_normal=plane_normal,
        vertex=vertex,
    )
    names = list(parameters) if parameters is not None else action.parameters
    return make_group_mixture_flow(
        group_action_fn=action,
        group_size=action.group_size,
        param_names=names,
        in_fundamental_domain=action.in_fundamental_domain,
    )
