"""Discrete symmetry transformations for the triangular Einstein Telescope.

nessai's :mod:`nessai.flowmodel.group_mixture` can learn a discrete mixture
over a finite symmetry group that acts on the (physical) parameters, letting
the normalising flow model a single mode while the mixture accounts for the
others.  This module provides the group for a single triangular detector such
as one Einstein Telescope (ET) site.

In the long-wavelength / "frozen" limit the extrinsic likelihood of a single
triangular detector is invariant under an eight-element group.  This is the
exact analogue of the LISA sky-mode degeneracy summarised in Table III (and
Eqs. 63-65) of

    S. Marsat, J. G. Baker and T. Dal Canton,
    "Exploring the Bayesian parameter estimation of binary black holes with
    LISA", Phys. Rev. D 103, 083011 (2021) [arXiv:2003.00357].

Writing ``(lambda, beta, psi)`` for the source azimuth, elevation and
polarisation *in the detector-plane frame* and ``iota`` for the inclination,
the group is generated by

* a rotation of the source azimuth by ``pi / 2`` about the detector normal,
  compensated by a ``pi / 2`` shift of the polarisation (Eq. 64)::

      lambda -> lambda + k pi / 2   (k = 0, 1, 2, 3)
      psi    -> psi    + k pi / 2

  (the ``m = +-2`` pattern functions pick up an overall sign under a
  quarter turn, which the polarisation shift undoes); and

* a reflection of the source through the detector plane (Eq. 63)::

      beta -> -beta,   psi -> pi - psi,   iota -> pi - iota

  (reflecting ``beta`` swaps ``F_+`` for a ``psi``-flipped response and
  flips the sign of ``F_x``, which ``iota -> pi - iota`` compensates for the
  dominant quadrupole).

The reference phase ``phase`` is unchanged by every element.  The four
rotations and the two reflection states give ``4 x 2 = 8`` elements; the
group is :math:`\\mathbb{Z}_4 \\times \\mathbb{Z}_2` (abelian).

Polarisation-phase coordinate
-----------------------------
For the dominant (2, 2) mode the extrinsic likelihood constrains only
``phase + sign(cos theta_jn) * psi`` (``phase + psi`` face-on, ``phase - psi``
face-off); the orthogonal combination is nearly flat.  The ET group wiring
therefore carries ``phase`` as the periodic coordinate
``delta_phase = phase + psi`` (:class:`~nessai_gw.reparameterisations.phase.PolarisationPhaseReparameterisation`,
``polarisation-phase``) so that ridge is an explicit flow axis and ``psi`` is
left as the broad orthogonal coordinate.  The map is *sign-free*: ``phase`` is
group-invariant, so with ``phase_inv = delta_phase_in - psi_in`` fixed,
:class:`PrimeSpaceETGroupAction` sets ``delta_phase_out = phase_inv + psi_out``
from the group-transformed ``psi`` (which the action returns).  A rotation gives
``psi_out ~ psi_in + k*pi/2`` hence ``delta_phase_out ~ delta_phase_in + k*pi/2``;
a reflection gives ``psi_out ~ pi - psi_in`` hence the face-on constrained
combination for the now-folded point -- no ``sign(cos theta_jn)`` branch, no
edge-on discontinuity.  It is a rotation of the Cartesian pair at fixed radius,
so the Jacobian stays 1.

Unlike LISA, a ground-based triangle sits at an appreciable offset
``r_ET`` from the geocenter, so the sky degeneracy is only a degeneracy of
the *detector-frame* arrival time, not of the geocentric time ``geocent_time``
that bilby samples.  With ``n`` the unit vector towards the source,

    geocent_time = t_det + (n . r_ET) / c

(Eq. 22 of Santoliquido et al. 2025, arXiv:2504.21087), so every element of
the group -- and in particular the plane reflection, which sends
``n . r_ET -> -n . r_ET`` for a near-radial site and thus produces the
bimodal ``geocent_time`` posterior of that paper -- must carry
``geocent_time`` along by the change in the geocenter-to-detector delay::

    geocent_time -> geocent_time + delay(n) - delay(n')

where ``n'`` is the transformed source direction and
``delay(n) = -(n . r_ET) / c`` is bilby's ``time_delay_from_geocenter``.  This is an additive shift
that depends only on the (already transformed) sky position, so it leaves the
Jacobian of the whole action equal to one.

The transformations act on the *geocentric* parameters used by bilby, but in
the measure-preserving coordinates ``ra``, ``sin_dec`` (``= sin(dec)``),
``cos_theta_jn`` (``= cos(theta_jn)``), ``psi``, ``phase`` and
``geocent_time``.  The sky
rotations/reflection are isometries of the sphere, so they preserve
``d(ra) d(sin_dec)``; the reflection sends ``cos_theta_jn -> -cos_theta_jn``;
and ``psi`` only picks up constant shifts and a sign flip.  The whole action
therefore has unit Jacobian in these coordinates -- which is what
:class:`nessai.flowmodel.group_mixture.DiscreteGroupMixtureFlowWrapper`
assumes (it treats the action as measure-preserving).  In the raw angles
``dec`` / ``theta_jn`` it would *not* be, and the omitted ``cos(dec)`` /
``sin(theta_jn)`` factors wreck the importance weights.

Points are carried into the detector-plane frame, transformed there, and
carried back, using exactly bilby's polarisation-tensor convention (Nishizawa
et al. 2009), so a transformed point reproduces the antenna response of the
original one.
"""

from __future__ import annotations

import numpy as np
import torch

from . import nessai_logger

logger = nessai_logger.getChild(__name__)

#: Parameters the group acts on, in the order expected by the flow.  These
#: are the *measure-preserving* coordinates: ``sin_dec = sin(dec)`` and
#: ``cos_theta_jn = cos(theta_jn)`` rather than the raw angles, so the action
#: has unit Jacobian (see the module docstring).
ET_TRIANGLE_PARAMETERS = [
    "ra",
    "sin_dec",
    "cos_theta_jn",
    "psi",
    "phase",
    "geocent_time",
]

#: Number of group elements.
ET_TRIANGLE_GROUP_SIZE = 8

#: Speed of light in m / s (CODATA / bilby ``speed_of_light``).
_SPEED_OF_LIGHT = 299792458.0

#: Geocentric position (metres, Earth-fixed frame) of the ``ET-EMR`` site,
#: WGS84 geodetic ``(lat, lon, height) = (50 deg 43' 23", 5 deg 55' 14", 0)``.
#: Used to convert between the detector-frame arrival time and bilby's
#: ``geocent_time``.  Recompute with :func:`detector_vertex` for a different
#: geometry.
ET_EMR_VERTEX = np.array(
    [4024345.21150611, 417334.87759012, 4914098.18878217]
)

#: Unit normal to the ET-EMR detector plane in the Earth-fixed (geocentric)
#: frame, ``mean_i normalise(x_arm_i x y_arm_i)`` for the three nested
#: interferometers of the ``ET-EMR`` triangle shipped with ``bilby_xG``
#: (Meuse-Rhine site, lat 50 deg 43' 23", lon 5 deg 55' 14").  Recompute with
#: :func:`detector_plane_normal` for a different geometry.
ET_EMR_PLANE_NORMAL = np.array(
    [0.6290179004039584, 0.06512521686797399, 0.7746581091603363]
)

_TWO_PI = 2.0 * np.pi

#: Small offset guarding divisions by a vector norm in the prime-space adapter.
_EPS = 1e-30

#: nessai ``Angle`` reparameterisation convention: the Cartesian angle stored by
#: the flow is ``physical_angle * scale``.  ``angle-pi`` (used for ``psi``) has
#: ``scale = 2``; ``angle-2pi`` (used for ``phase``) has ``scale = 1``.  The ET
#: group wiring replaces ``phase`` with ``delta_phase = phase + psi``
#: (``polarisation-phase``, also an ``angle-2pi``-style periodic coordinate);
#: the ``"phase"`` key is kept so :func:`_decode_pair` stays generic.
_ANGLE_SCALE = {"psi": 2.0, "phase": 1.0, "delta_phase": 1.0}

#: ``geocent_time`` prime coordinate is ``(geocent_time - reference_time) /
#: _GEOCENT_SCALE``.  A fixed scale (rather than data-driven bounds) keeps the
#: group's additive light-travel-delay shift exact under a constant offset.
_GEOCENT_SCALE = 5e-3

#: Floor for the group-mixture wrapper's per-element canonical std.  Lowered
#: from nessai's ``1e-2`` default so a genuinely narrow prime dimension
#: (``geocent_time``) is standardised by its real width, not the floor.
_MIN_CANON_STD = 1e-3


def detector_plane_normal(interferometers) -> np.ndarray:
    """Unit normal to the plane of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects (the three
        nested detectors of the triangle), each exposing ``geometry.x`` and
        ``geometry.y`` unit arm vectors in the Earth-fixed frame.

    Returns
    -------
    numpy.ndarray
        The mean arm-plane normal, normalised to unit length.
    """
    normals = []
    for ifo in interferometers:
        x = np.asarray(ifo.geometry.x, dtype=float)
        y = np.asarray(ifo.geometry.y, dtype=float)
        n = np.cross(x, y)
        normals.append(n / np.linalg.norm(n))
    n = np.mean(normals, axis=0)
    return n / np.linalg.norm(n)


def detector_vertex(interferometers) -> np.ndarray:
    """Mean geocentric vertex position (metres) of a triangular interferometer.

    Parameters
    ----------
    interferometers : iterable
        Iterable of bilby / bilby_xG ``Interferometer`` objects, each exposing
        ``geometry.vertex`` (its Earth-fixed position in metres).

    Returns
    -------
    numpy.ndarray
        The mean of the three vertex positions.
    """
    vertices = [
        np.asarray(ifo.geometry.vertex, dtype=float) for ifo in interferometers
    ]
    return np.mean(vertices, axis=0)


def detector_vertex_from_geodetic(
    latitude: float, longitude: float, height: float = 0.0
) -> np.ndarray:
    """Earth-fixed position (metres) from WGS84 geodetic coordinates.

    Parameters
    ----------
    latitude, longitude : float
        Geodetic latitude and longitude in radians.
    height : float, optional
        Height above the WGS84 ellipsoid in metres (default 0).
    """
    a = 6378137.0
    f = 1.0 / 298.257223563
    e2 = f * (2.0 - f)
    sin_lat = np.sin(latitude)
    n = a / np.sqrt(1.0 - e2 * sin_lat**2)
    return np.array(
        [
            (n + height) * np.cos(latitude) * np.cos(longitude),
            (n + height) * np.cos(latitude) * np.sin(longitude),
            (n * (1.0 - e2) + height) * sin_lat,
        ]
    )


def _greenwich_mean_sidereal_time(gps_time: float) -> float:
    """GMST in radians at ``gps_time`` (via bilby if it is available)."""
    try:
        from bilby_cython.time import greenwich_mean_sidereal_time

        return float(greenwich_mean_sidereal_time(gps_time)) % _TWO_PI
    except Exception:  # pragma: no cover - fallback only
        # IAU 1982 GMST, adequate (<~1 arcmin) for a discrete-mode proposal.
        jd = gps_time / 86400.0 + 2444244.5
        t = (jd - 2451545.0) / 36525.0
        gmst_seconds = (
            67310.54841
            + (876600.0 * 3600.0 + 8640184.812866) * t
            + 0.093104 * t**2
            - 6.2e-6 * t**3
        )
        return (gmst_seconds * np.pi / 43200.0) % _TWO_PI


def _detector_frame_basis(plane_normal: np.ndarray) -> np.ndarray:
    """Orthonormal Earth-fixed basis ``[e1, e2, e3]`` with ``e3`` the normal.

    ``e1`` is the (Earth-fixed) z-axis projected into the plane.  The choice
    of in-plane axes only shifts ``lambda`` and ``psi`` by a constant, which
    the group action is equivariant under, so it does not matter.
    """
    e3 = np.asarray(plane_normal, dtype=float)
    e3 = e3 / np.linalg.norm(e3)
    e1 = np.array([0.0, 0.0, 1.0]) - e3[2] * e3
    e1 = e1 / np.linalg.norm(e1)
    e2 = np.cross(e3, e1)
    return np.stack([e1, e2, e3])


def _uvw(phi: torch.Tensor, theta: torch.Tensor):
    """bilby (Nishizawa 2009) frame vectors for colatitude/azimuth angles."""
    cp, sp = torch.cos(phi), torch.sin(phi)
    ct, st = torch.cos(theta), torch.sin(theta)
    zero = torch.zeros_like(phi)
    u = torch.stack([cp * ct, ct * sp, -st], dim=-1)
    v = torch.stack([-sp, cp, zero], dim=-1)
    w = torch.stack([st * cp, st * sp, ct], dim=-1)
    return u, v, w


def _polarisation_angle(m: torch.Tensor, u: torch.Tensor, v: torch.Tensor):
    """Recover ``psi`` from ``m``, where ``m = -u sin psi - v cos psi``."""
    return torch.atan2(-(m * u).sum(-1), -(m * v).sum(-1))


class ETTriangleGroupAction:
    """Callable eight-element group action for a triangular detector.

    Instances are the ``group_action_fn`` /  ``in_fundamental_domain`` pair
    consumed by :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event.  Only the Greenwich mean sidereal
        time it implies is used (to rotate between the equatorial and
        Earth-fixed frames); the ~tens-of-ms spread of a posterior is
        negligible here.
    plane_normal : array_like, optional
        Unit normal to the detector plane in the Earth-fixed frame.  Defaults
        to :data:`ET_EMR_PLANE_NORMAL`.  Use :func:`detector_plane_normal` to
        build one from a bilby interferometer list.
    vertex : array_like, optional
        Geocentric position of the detector (metres, Earth-fixed frame), used
        to carry ``geocent_time`` along with the sky transformation.  Defaults
        to :data:`ET_EMR_VERTEX`.  Use :func:`detector_vertex` to build one
        from a bilby interferometer list.
    """

    parameters = ET_TRIANGLE_PARAMETERS
    group_size = ET_TRIANGLE_GROUP_SIZE

    def __init__(self, reference_time, plane_normal=None, vertex=None):
        self.reference_time = float(reference_time)
        self.gmst = _greenwich_mean_sidereal_time(self.reference_time)
        if plane_normal is None:
            plane_normal = ET_EMR_PLANE_NORMAL
        self.plane_normal = np.asarray(plane_normal, dtype=float)
        self._basis_np = _detector_frame_basis(self.plane_normal)
        self._basis = torch.as_tensor(self._basis_np, dtype=torch.float64)
        if vertex is None:
            vertex = ET_EMR_VERTEX
        self.vertex = np.asarray(vertex, dtype=float)
        self._vertex = torch.as_tensor(self.vertex, dtype=torch.float64)

    # -- coordinate maps ------------------------------------------------

    def _to_frame(self, ra, dec, psi):
        """Equatorial ``(ra, dec, psi)`` -> detector-frame angles."""
        basis = self._basis.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        u, v, w = _uvw(phi, theta)
        m = -u * torch.sin(psi)[..., None] - v * torch.cos(psi)[..., None]
        w_f = w @ basis.T
        m_f = m @ basis.T
        theta_f = torch.acos(torch.clamp(w_f[..., 2], -1.0, 1.0))
        lam_f = torch.atan2(w_f[..., 1], w_f[..., 0])
        u_f, v_f, _ = _uvw(lam_f, theta_f)
        psi_f = _polarisation_angle(m_f, u_f, v_f)
        beta_f = 0.5 * np.pi - theta_f
        return lam_f, beta_f, psi_f

    def _from_frame(self, lam_f, beta_f, psi_f):
        """Detector-frame angles -> equatorial ``(ra, dec, psi)``."""
        basis = self._basis.to(lam_f.dtype)
        theta_f = 0.5 * np.pi - beta_f
        u_f, v_f, w_f = _uvw(lam_f, theta_f)
        sin_psi = torch.sin(psi_f)[..., None]
        cos_psi = torch.cos(psi_f)[..., None]
        m_f = -u_f * sin_psi - v_f * cos_psi
        w = w_f @ basis
        m = m_f @ basis
        dec = torch.asin(torch.clamp(w[..., 2], -1.0, 1.0))
        phi = torch.atan2(w[..., 1], w[..., 0])
        ra = torch.remainder(phi + self.gmst, _TWO_PI)
        u, v, _ = _uvw(ra - self.gmst, 0.5 * np.pi - dec)
        psi = torch.remainder(_polarisation_angle(m, u, v), np.pi)
        return ra, dec, psi

    def _geocenter_delay(self, ra, dec):
        """Geocenter-to-detector light-travel delay ``t_det - geocent_time``.

        Equal to ``-(n . r_ET) / c`` with ``n`` the unit vector towards the
        source, matching bilby's ``time_delay_from_geocenter`` convention.
        """
        vertex = self._vertex.to(ra.dtype)
        phi = ra - self.gmst
        theta = 0.5 * np.pi - dec
        st = torch.sin(theta)
        n = torch.stack(
            [st * torch.cos(phi), st * torch.sin(phi), torch.cos(theta)],
            dim=-1,
        )
        return -(n * vertex).sum(-1) / _SPEED_OF_LIGHT

    # -- group action -------------------------------------------------

    @staticmethod
    def _decode(modes: torch.Tensor):
        """Split a mode index in ``0..7`` into ``(k, reflected)``."""
        k = torch.remainder(modes, 4).to(torch.float64)
        reflected = (torch.div(modes, 4, rounding_mode="floor") == 1)
        return k, reflected

    @staticmethod
    def _invert_modes(modes: torch.Tensor) -> torch.Tensor:
        """Index of the inverse element (the group is abelian)."""
        k = torch.remainder(modes, 4)
        refl = torch.div(modes, 4, rounding_mode="floor")
        return refl * 4 + torch.remainder(-k, 4)

    # Public aliases of the mode helpers, for callers (e.g.
    # :class:`PrimeSpaceETGroupAction`) that need to inspect group elements
    # without reaching into private names.
    @staticmethod
    def decode_modes(modes):
        """Split a mode index in ``0..7`` into ``(k, reflected)``."""
        return ETTriangleGroupAction._decode(torch.as_tensor(modes))

    @staticmethod
    def invert_modes(modes):
        """Index of the inverse element (the group is abelian)."""
        return ETTriangleGroupAction._invert_modes(torch.as_tensor(modes))

    def __call__(self, point_dict: dict, modes, inverse: bool = False) -> dict:
        """Apply the group element ``modes`` (or its inverse) to each point."""
        ra = point_dict["ra"]
        sin_dec = point_dict["sin_dec"]
        psi = point_dict["psi"]
        cos_theta_jn = point_dict["cos_theta_jn"]
        phase = point_dict["phase"]
        geocent_time = point_dict["geocent_time"]

        dec = torch.asin(torch.clamp(sin_dec, -1.0, 1.0))

        modes = torch.as_tensor(modes, device=ra.device)
        if inverse:
            modes = self._invert_modes(modes)
        k, reflected = self._decode(modes)
        k = k.to(ra.dtype)
        quarter = 0.5 * np.pi * k

        lam_f, beta_f, psi_f = self._to_frame(ra, dec, psi)

        lam_f = lam_f + quarter
        beta_f = torch.where(reflected, -beta_f, beta_f)
        psi_f = torch.where(reflected, np.pi - psi_f, psi_f) + quarter
        # theta_jn -> pi - theta_jn under a reflection, i.e. a sign flip of
        # cos(theta_jn) -- unit Jacobian in this coordinate.
        cos_theta_jn = torch.where(
            reflected, -cos_theta_jn, cos_theta_jn
        )

        ra_t, dec_t, psi_t = self._from_frame(lam_f, beta_f, psi_f)

        # The sky degeneracy fixes the detector-frame arrival time, not the
        # geocentric one: shift geocent_time by the change in the
        # geocenter-to-detector delay (Santoliquido et al. 2025, Eq. 22).
        geocent_time_t = (
            geocent_time
            + self._geocenter_delay(ra, dec)
            - self._geocenter_delay(ra_t, dec_t)
        )

        return {
            "ra": ra_t,
            "sin_dec": torch.sin(dec_t),
            "cos_theta_jn": cos_theta_jn,
            "psi": psi_t,
            "phase": phase,
            "geocent_time": geocent_time_t,
        }

    def in_fundamental_domain(self, point_dict: dict) -> torch.Tensor:
        """Boolean mask: is each point the canonical point of its orbit?

        The canonical point is the one whose detector-frame azimuth lies in
        ``[0, pi / 2)`` and which sits on the ``beta >= 0`` side of the
        detector plane -- exactly one of the eight images of a generic point.
        """
        dec = torch.asin(torch.clamp(point_dict["sin_dec"], -1.0, 1.0))
        lam_f, beta_f, _ = self._to_frame(
            point_dict["ra"], dec, point_dict["psi"]
        )
        in_quarter = torch.remainder(lam_f, _TWO_PI) < 0.5 * np.pi
        return in_quarter & (beta_f >= 0.0)


def make_et_triangle_group_mixture_flow(
    reference_time, plane_normal=None, vertex=None, parameters=None
):
    """Build a group-mixture ``FlowModel`` class for a triangular detector.

    Thin wrapper around
    :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow` bound to
    :class:`ETTriangleGroupAction`.

    Parameters
    ----------
    reference_time : float
        Geocentric GPS time of the event (see :class:`ETTriangleGroupAction`).
    plane_normal : array_like, optional
        Earth-fixed unit normal to the detector plane; defaults to
        :data:`ET_EMR_PLANE_NORMAL`.
    vertex : array_like, optional
        Geocentric detector position (metres); defaults to
        :data:`ET_EMR_VERTEX`.
    parameters : list of str, optional
        Override the acted-on parameter names/order (default
        :data:`ET_TRIANGLE_PARAMETERS`).  The flow must be given exactly
        these inputs, in this order.

    Returns
    -------
    type
        A ``GroupMixtureFlowModel`` subclass, suitable as ``_FlowModelClass``
        of a :class:`nessai.flowmodel.group_mixture.GroupFlowProposal` (or the
        ``flow_class`` of a flow config).
    """
    from nessai.flowmodel.group_mixture import make_group_mixture_flow

    action = ETTriangleGroupAction(
        reference_time=reference_time,
        plane_normal=plane_normal,
        vertex=vertex,
    )
    names = list(parameters) if parameters is not None else action.parameters
    return make_group_mixture_flow(
        group_action_fn=action,
        group_size=action.group_size,
        param_names=names,
        in_fundamental_domain=action.in_fundamental_domain,
    )


# ---------------------------------------------------------------------------
# Prime-space adapter + proposal wiring
#
# nessai's :class:`~nessai.flowmodel.group_mixture.GroupFlowProposalMixin` can
# run :class:`ETTriangleGroupAction` directly in the *physical* parameter space
# and bridge to the flow's *prime* space with a
# :class:`~nessai.flowmodel.group_mixture.ReparamBridge` (non-affine
# reparameterisations handled exactly).  That is the ``prime_space=False`` path
# of :func:`make_et_group_flow_proposal` and needs no code here.
#
# The ``prime_space=True`` path instead maps the acted physical coordinates out
# of the nessai-gw prime vector, runs the unchanged group action, and re-encodes
# onto vectors of the *same* radii -- an exact unit-Jacobian prime-space map with
# no per-call numpy round-trip through the reparameterisation.  This mirrors the
# wiring tuned in the ``xG_inference`` ET replay optimisation.
# ---------------------------------------------------------------------------


def _angle_from_pair(x, y, scale):
    """Physical angle from a nessai ``Angle`` Cartesian pair (radius returned)."""
    radius = torch.hypot(x, y)
    angle = torch.remainder(torch.atan2(y, x), _TWO_PI) / scale
    return angle, radius


def _pair_from_angle(angle, radius, scale):
    """Inverse of :func:`_angle_from_pair`."""
    a = angle * scale
    return radius * torch.cos(a), radius * torch.sin(a)


def _decode_pair(point_dict, pair, scale):
    x, y = point_dict[pair[0]], point_dict[pair[1]]
    return _angle_from_pair(x, y, scale)


class PrimeSpaceETGroupAction:
    """Apply :class:`ETTriangleGroupAction` in the nessai-gw *prime* space.

    Discovers the sky / ``psi`` / ``phase`` / ``theta_jn`` / ``geocent_time``
    prime coordinates from the flow's actual ``prime_parameters`` and threads
    the acted subset through the unchanged group action, re-encoding onto
    same-radius vectors so the prime-space map is exactly a rotation /
    reflection / constant shift with unit Jacobian.

    Instances are passed to
    :func:`nessai.flowmodel.group_mixture.make_group_mixture_flow` as the
    ``prime_space_action`` / ``prime_space_in_domain`` pair.

    Parameters
    ----------
    action : ETTriangleGroupAction
        The physical-space group action.
    prime_names : list of str
        The flow's prime-parameter names, in order.  Re-bind after the proposal
        is initialised with :meth:`bind`.
    """

    def __init__(self, action, prime_names):
        self._action = action
        self.bind(prime_names)

    # -- binding -----------------------------------------------------------

    def bind(self, prime_names):
        """(Re)bind to the flow's actual prime-parameter order."""
        self._prime_names = list(prime_names)
        names = set(self._prime_names)

        # sky: ra_dec_{x,y,z} from the sky-ra-dec AnglePair
        self._sky = None
        for prefix in ("ra_dec", "dec_ra"):
            trip = [f"{prefix}_{c}" for c in ("x", "y", "z")]
            if all(t in names for t in trip):
                self._sky = tuple(trip)
                break

        # psi / delta_phase: name_{x,y} from the angle-pi / polarisation-phase
        # Angle reparams
        self._pair = {}
        for base in _ANGLE_SCALE:
            x, y = f"{base}_x", f"{base}_y"
            if x in names and y in names:
                self._pair[base] = (x, y)

        # theta_jn: single linear angle-sine coordinate
        self._theta_jn = None
        for cand in ("theta_jn_prime", "theta_jn"):
            if cand in names:
                self._theta_jn = cand
                break

        # geocent_time: single constant-shifted coordinate
        self._geocent_time = None
        for cand in ("geocent_time_prime", "geocent_time"):
            if cand in names:
                self._geocent_time = cand
                break

        missing = []
        if self._sky is None:
            missing.append("sky-ra-dec (ra_dec_x/_y/_z)")
        if "psi" not in self._pair:
            missing.append("psi (psi_x/_y)")
        if "delta_phase" not in self._pair:
            missing.append("delta_phase (delta_phase_x/_y)")
        if self._theta_jn is None:
            missing.append("theta_jn")
        if self._geocent_time is None:
            missing.append("geocent_time")
        if missing:
            raise RuntimeError(
                f"prime space is missing {missing}, which the ET group action "
                "needs; the prime-space path only applies to a single-site "
                "ET-triangle run with the standard extrinsic parameters and "
                "the nessai-gw reparameterisations (sky-ra-dec, angle-pi, "
                "polarisation-phase, angle-sine)."
            )

    # -- decode / encode -------------------------------------------------

    def _decode(self, point_dict):
        """nessai-gw prime dict -> ``ETTriangleGroupAction`` coordinate dict.

        Returns ``(acted, aux)`` where ``aux`` carries the radii needed to
        re-encode.
        """
        sx, sy, sz = (point_dict[n] for n in self._sky)
        r_sky = torch.sqrt(sx * sx + sy * sy + sz * sz + _EPS)
        ra = torch.remainder(torch.atan2(sy, sx), _TWO_PI)
        sin_dec = torch.clamp(sz / r_sky, -1.0, 1.0)

        psi, r_psi = _decode_pair(
            point_dict, self._pair["psi"], _ANGLE_SCALE["psi"]
        )

        # theta_jn is decoupled from the frame rotation: the group only ever
        # sends cos(theta_jn) -> -cos(theta_jn) under a reflection, i.e. the
        # angle-sine coordinate u -> -u (centre 0).  Handled directly in
        # :meth:`_encode`; the value passed to the action is a dummy.
        cos_theta_jn = torch.zeros_like(ra)

        # phase is group-invariant, but the flow carries delta_phase = phase +
        # psi (polarisation-phase).  Recover the invariant physical phase and
        # feed it through; :meth:`_encode` rebuilds delta_phase from the mapped
        # psi so the reflection's psi -> pi - psi flows into it automatically.
        delta_phase, r_dphase = _decode_pair(
            point_dict, self._pair["delta_phase"], _ANGLE_SCALE["delta_phase"]
        )
        phase = delta_phase - psi

        # prime -> seconds; the action uses geocent_time only additively, so the
        # constant reference_time offset need not be restored -- only the scale.
        geocent_time = point_dict[self._geocent_time] * _GEOCENT_SCALE

        acted = {
            "ra": ra,
            "sin_dec": sin_dec,
            "cos_theta_jn": cos_theta_jn,
            "psi": psi,
            "phase": phase,
            "geocent_time": geocent_time,
        }
        aux = {
            "r_sky": r_sky,
            "r_psi": r_psi,
            "r_dphase": r_dphase,
            "phase_inv": phase,
        }
        return acted, aux

    def _encode(self, point_dict, mapped, aux):
        out = dict(point_dict)

        ra_t = mapped["ra"]
        sin_dec_t = torch.clamp(mapped["sin_dec"], -1.0, 1.0)
        cos_dec_t = torch.sqrt(torch.clamp(1.0 - sin_dec_t ** 2, min=0.0))
        r = aux["r_sky"]
        sx, sy, sz = self._sky
        out[sx] = r * cos_dec_t * torch.cos(ra_t)
        out[sy] = r * cos_dec_t * torch.sin(ra_t)
        out[sz] = r * sin_dec_t

        px, py = self._pair["psi"]
        out[px], out[py] = _pair_from_angle(
            mapped["psi"], aux["r_psi"], _ANGLE_SCALE["psi"]
        )

        # delta_phase = phase_invariant + psi_out.  No sign / reflected term:
        # the reflection's psi -> pi - psi arrives through mapped["psi"].
        dpx, dpy = self._pair["delta_phase"]
        delta_phase_new = aux["phase_inv"] + mapped["psi"]
        out[dpx], out[dpy] = _pair_from_angle(
            delta_phase_new, aux["r_dphase"], _ANGLE_SCALE["delta_phase"]
        )

        u = point_dict[self._theta_jn]
        out[self._theta_jn] = torch.where(aux["reflected"], -u, u)

        out[self._geocent_time] = mapped["geocent_time"] / _GEOCENT_SCALE
        return {n: out[n] for n in self._prime_names}

    # -- interface ------------------------------------------------------

    def _reflected_mask(self, modes, inverse):
        modes = torch.as_tensor(modes)
        if inverse:
            modes = self._action.invert_modes(modes)
        _, reflected = self._action.decode_modes(modes)
        return reflected

    def __call__(self, point_dict, modes, inverse: bool = False):
        acted, aux = self._decode(point_dict)
        mapped = self._action(acted, modes, inverse=inverse)
        aux["reflected"] = self._reflected_mask(modes, inverse)
        return self._encode(point_dict, mapped, aux)

    def in_fundamental_domain(self, point_dict):
        acted, _ = self._decode(point_dict)
        return self._action.in_fundamental_domain(acted)


def et_group_reparameterisations(sampling_parameters, reference_time):
    """Reparameterisation overrides that keep the acted parameters isometric.

    The ET group action has unit Jacobian in
    ``(ra, sin_dec, cos_theta_jn, psi, phase, geocent_time)``.  Each of those
    maps to the nessai-gw prime coordinates by an isometry *provided* the right
    reparameterisation is used:

    * ``chi_1`` / ``chi_2`` -> ``aligned-spin`` (nessai-gw CDF -> inverse-normal
      map; standard-normal prime prior, removes the log cusp at ``chi = 0``).
    * ``lambda_1`` / ``lambda_2`` -> ``logit`` with ``update_bounds=False``
      (fixed hard bounds, prime coordinate on the whole real line).
    * ``theta_jn`` -> ``angle-sine`` with ``update_bounds=False``.  The fixed,
      symmetric bounds keep the group's ``theta_jn -> pi - theta_jn`` reflection
      an exact sign flip of the prime coordinate; ``update_bounds=True`` would
      let the empirical bounds drift off ``pi/2`` and break that.
    * ``geocent_time`` -> constant ``reference_time`` shift with a fixed
      :data:`_GEOCENT_SCALE` (keeps the GPS epoch off the flow; the group's own
      additive light-travel-delay shift is unaffected by a constant offset).
    * ``phase`` -> ``polarisation-phase`` (periodic ``delta_phase = phase + psi``
      pair): makes the likelihood-constrained polarisation/phase combination an
      explicit flow axis instead of a thin diagonal ridge across four prime
      coordinates.  ``psi`` (``angle-pi``) is a prerequisite of this coordinate.

    Every other parameter is left to
    :meth:`nessai_gw.proposals.GWReparamMixin.add_default_reparameterisations`
    (``sky-ra-dec`` for ``ra``/``dec``, ``angle-pi`` for ``psi``,
    ``distance`` / ``mass`` for the intrinsic parameters, ...).

    Parameters
    ----------
    sampling_parameters : iterable of str
        Every parameter nessai samples.
    reference_time : float
        Geocentric GPS time subtracted from ``geocent_time`` in prime space.

    Returns
    -------
    dict
        A ``reparameterisations`` mapping for ``bilby.run_sampler`` / nessai.
    """
    reps = {}
    for name in sampling_parameters:
        if name in ("chi_1", "chi_2"):
            reps[name] = {"reparameterisation": "aligned-spin"}
        elif name in ("lambda_1", "lambda_2"):
            reps[name] = {
                "reparameterisation": "logit",
                "update_bounds": False,
            }
        elif name == "theta_jn":
            reps[name] = {
                "reparameterisation": "angle-sine",
                "update_bounds": False,
            }
        elif name == "geocent_time":
            reps[name] = {
                "reparameterisation": "scaleandshift",
                "scale": _GEOCENT_SCALE,
                "shift": float(reference_time),
            }
        elif name == "phase":
            # delta_phase = phase + psi (polarisation-phase): makes the
            # likelihood-constrained polarisation/phase combination an explicit
            # flow axis.  ``psi`` (its default ``angle-pi``) is a prerequisite.
            reps[name] = {"reparameterisation": "polarisation-phase"}
    return reps


#: Dummy prior bounds for the throwaway reparameterisation build in
#: :func:`_prime_parameter_names`.  Values are irrelevant; each just has to be a
#: finite range valid for that parameter's reparameterisation.
_DUMMY_PRIOR_BOUNDS = {
    "ra": (0.0, _TWO_PI),
    "dec": (-np.pi / 2, np.pi / 2),
    "theta_jn": (0.0, np.pi),
    "iota": (0.0, np.pi),
    "tilt_1": (0.0, np.pi),
    "tilt_2": (0.0, np.pi),
    "psi": (0.0, np.pi),
    # ``phase`` bounds also serve the derived ``delta_phase`` coordinate
    # (``polarisation-phase``), which needs no entry of its own.
    "phase": (0.0, _TWO_PI),
    "phi_12": (0.0, _TWO_PI),
    "phi_jl": (0.0, _TWO_PI),
    "a_1": (0.0, 0.99),
    "a_2": (0.0, 0.99),
    "chi_1": (-0.99, 0.99),
    "chi_2": (-0.99, 0.99),
    "luminosity_distance": (10.0, 5000.0),
    "chirp_mass": (1.0, 2.0),
    "mass_ratio": (0.125, 1.0),
    "mass_1": (1.0, 3.0),
    "mass_2": (1.0, 3.0),
    "lambda_1": (0.0, 2500.0),
    "lambda_2": (0.0, 2500.0),
}


def _prime_parameter_names(sampling_parameters, reference_time):
    """Prime-parameter names *and order* nessai produces for this wiring.

    Computed by configuring a throwaway
    :class:`nessai_gw.proposals.GWFlowProposal` with the same
    reparameterisation dict / fallback the real proposal uses and reading back
    ``prime_parameters``.  The order matters: the group-mixture wrapper builds
    its base-flow ``point_dict`` from ``param_names`` before
    :meth:`ETGroupFlowProposal.initialise` re-binds to the live
    ``prime_parameters``.

    Falls back to a name-order heuristic (right count, order not guaranteed) if
    the throwaway build fails.
    """
    names = list(sampling_parameters)

    try:
        from nessai.model import Model

        from .proposals import GWFlowProposal

        bounds = {
            name: np.asarray(
                _DUMMY_PRIOR_BOUNDS.get(name, (0.0, 1.0)), dtype=float
            )
            for name in names
        }

        class _StubModel(Model):
            def __init__(self):
                self.names = list(names)
                self.bounds = bounds

            def log_prior(self, x):
                return np.zeros(len(np.atleast_1d(x)))

            def log_likelihood(self, x):
                return np.zeros(len(np.atleast_1d(x)))

        probe = GWFlowProposal(
            _StubModel(),
            poolsize=100,
            reparameterisations=et_group_reparameterisations(
                names, reference_time
            ),
            fallback_reparameterisation="zscore",
        )
        probe.set_rescaling()
        prime = list(probe.prime_parameters)
        if prime:
            return prime
    except Exception as exc:  # pragma: no cover - defensive
        import warnings

        warnings.warn(
            "Could not probe nessai for the real prime-parameter order "
            f"({exc!r}); falling back to a name-order heuristic. Buffers are "
            "re-bound at initialise, so only the pre-bind placeholder is "
            "affected.",
            RuntimeWarning,
        )

    out = []
    if "ra" in names and "dec" in names:
        out += ["ra_dec_x", "ra_dec_y", "ra_dec_z"]
    for name in names:
        if name in ("ra", "dec"):
            continue
        # the ET wiring reparameterises ``phase`` as ``delta_phase = phase + psi``
        coord = "delta_phase" if name == "phase" else name
        if coord in _ANGLE_SCALE:
            out += [f"{coord}_x", f"{coord}_y"]
        else:
            out.append(f"{coord}_prime")
    return out


def make_et_group_flow_proposal(
    sampling_parameters,
    reference_time,
    plane_normal=None,
    vertex=None,
    prime_space=True,
):
    """Build a ``FlowProposal`` subclass wired for the ET-triangle group mixture.

    The returned class combines :class:`nessai_gw.proposals.GWReparamMixin`
    (GW reparameterisations by parameter name),
    :class:`nessai.flowmodel.group_mixture.GroupFlowProposalMixin` (group-mixture
    wiring) and :class:`nessai.proposal.FlowProposal`, with
    :class:`ETTriangleGroupAction` as the group action.  Pass it as
    ``flow_proposal_class`` to ``bilby.run_sampler(sampler="nessai", ...)``
    together with :func:`et_group_reparameterisations`.

    Parameters
    ----------
    sampling_parameters : list of str
        Every parameter nessai samples, in order.  Must contain ``ra``, ``dec``,
        ``theta_jn``, ``psi``, ``phase`` and ``geocent_time``.
    reference_time : float
        Geocentric GPS time of the event.
    plane_normal : array_like, optional
        Earth-fixed unit normal to the detector plane; defaults to
        :data:`ET_EMR_PLANE_NORMAL`.
    vertex : array_like, optional
        Geocentric detector position (metres); defaults to :data:`ET_EMR_VERTEX`.
    prime_space : bool, optional
        If ``True`` (default) run the action in the flow's prime space via
        :class:`PrimeSpaceETGroupAction` (exact unit Jacobian, no per-call numpy
        round-trip).  If ``False`` run it in physical coordinates and let
        nessai's ``GroupFlowProposalMixin`` bridge to prime space with a
        ``ReparamBridge``.
    """
    try:
        from nessai.proposal import FlowProposal
        from nessai.flowmodel.group_mixture import (
            GroupFlowProposalMixin,
            make_group_mixture_flow,
        )
    except ImportError as exc:  # pragma: no cover - depends on nessai version
        raise RuntimeError(
            "make_et_group_flow_proposal requires a version of nessai that "
            "ships nessai.flowmodel.group_mixture (GroupFlowProposalMixin, "
            "make_group_mixture_flow)."
        ) from exc

    from .proposals import GWReparamMixin

    names = list(sampling_parameters)
    missing = sorted(
        {"ra", "dec", "theta_jn", "psi", "phase", "geocent_time"} - set(names)
    )
    if missing:
        raise RuntimeError(
            f"The sampling space is missing {missing}, which the ET group "
            "action needs; this proposal only applies to a single-site "
            "ET-triangle run with the standard extrinsic parameters."
        )

    base_action = ETTriangleGroupAction(
        reference_time=reference_time,
        plane_normal=plane_normal,
        vertex=vertex,
    )

    if prime_space:
        prime_names = _prime_parameter_names(names, reference_time)
        action = PrimeSpaceETGroupAction(base_action, prime_names)
        flow_model_cls = make_group_mixture_flow(
            group_action_fn=action,  # ignored on the prime-space path
            group_size=ETTriangleGroupAction.group_size,
            param_names=prime_names,
            prime_space_action=action,
            prime_space_in_domain=action.in_fundamental_domain,
            min_canon_std=_MIN_CANON_STD,
        )
    else:
        action = None
        flow_model_cls = make_group_mixture_flow(
            group_action_fn=base_action,
            group_size=base_action.group_size,
            param_names=base_action.parameters,
            in_fundamental_domain=base_action.in_fundamental_domain,
            min_canon_std=_MIN_CANON_STD,
        )

    class ETGroupFlowProposal(
        GWReparamMixin, GroupFlowProposalMixin, FlowProposal
    ):
        """``FlowProposal`` wired for the ET-triangle group-mixture flow with
        the nessai-gw GW reparameterisations."""

        _FlowModelClass = flow_model_cls

        def initialise(self, *args, **kwargs):
            super().initialise(*args, **kwargs)
            if action is None:
                return
            # Realign the prime-space action to nessai's actual prime parameter
            # order (do not assume the reparameterisation-dict order).
            model = getattr(self.flow, "model", None)
            prime = list(getattr(self, "prime_parameters", []) or [])
            if model is not None and prime:
                action.bind(prime)
                model.param_names = prime

    # nessai checkpoints the sampler (hence the proposal *instance*) with
    # ``pickle``, which resolves an instance's class by ``module.__qualname__``.
    # Publish this otherwise-local class at module scope under a stable name.
    ETGroupFlowProposal.__module__ = __name__
    ETGroupFlowProposal.__qualname__ = "ETGroupFlowProposal"
    globals()["ETGroupFlowProposal"] = ETGroupFlowProposal
    return ETGroupFlowProposal
